import 'package:flutter/material.dart';

class LocalizationService extends ChangeNotifier {
  static final LocalizationService _instance = LocalizationService._internal();
  factory LocalizationService() => _instance;
  LocalizationService._internal();

  String _currentLanguage = 'English';
  String get currentLanguage => _currentLanguage;

  final Map<String, Map<String, String>> _translations = {
    'English': {
      'dashboard': 'Dashboard',
      'kds': 'KDS',
      'reservation': 'Reservation',
      'orders': 'Orders',
      'tables': 'Tables',
      'pos': 'POS',
      'waiting': 'Waiting',
      'settings': 'Settings',
      'edit': 'Edit',
      'export_pdf': 'Export PDF',
      'view_details': 'View Details',
      'midnight_blue': 'Midnight Blue',
      'emerald_green': 'Emerald Green',
      'aura_purple': 'Aura Purple',
      'dark_mode': 'Dark Mode',
      'printer_settings': 'Printer Settings',
      'sound_settings': 'Sound Settings',
      'auto_logout': 'Auto Logout',
      'language': 'Language',
      'mission_control': 'Mission Control Center',
      'terminal': 'Terminal',
      'close': 'Close',
      'attention': 'Attention',
      'add_items_to_cart_warning': 'Please add items to your cart before proceeding.',
      'select_table_warning': 'Please select a table for this Dine-In order.',
      'select_waiter_warning': 'Please select a waiter for this order.',
      'enter_guest_name_warning': 'Please enter the guest name.',
      'enter_guest_phone_warning': 'Please enter the guest phone number.',
      'enter_table_number_warning': 'Please enter a table number.',
      'enter_capacity_warning': 'Please specify table capacity.',
      'fill_guest_details_warning': 'Please provide both Name and Phone number to continue.',
      'ok': 'OK',
      'save_settings': 'Save Settings',
      'save_changes': 'Save Changes',
      'cancel': 'Cancel',
      'mark_all_read': 'Mark All Read',
      'user_profile': 'User Profile',
      'terminal_id': 'Terminal #',
      'role_admin': 'Role: Administrator',
      'logout_not_connected': 'Logout functionality not connected',
      'provide_rejection_reason': 'Please provide a reason for rejecting order',
      'network': 'Network',
      'bluetooth': 'Bluetooth',
      'usb': 'USB',
      'test_print_sent': 'Test print sent!',
      'invalid_ip_format': 'Invalid IP Address format',
      'notifications': 'Notifications',
      'main_course_items': 'Main Course Items',
      'updating_order': 'Updating Order',
      'demo_mode_desc': 'DEMO MODE: Showing sample signature items',
      'browse_menu_desc': 'Browse menu items and add them to the current order',
      'cancel_edit': 'CANCEL EDIT',
      'all_items': 'All Items',
      'cart_details': 'Cart Details',
      'empty_cart': 'Your cart is empty',
      'checkout': 'Checkout',
      'total': 'Total',
      'subtotal': 'Subtotal',
      'tax': 'Tax',
      'discount': 'Discount',
      'tip': 'Tip',
      'add_to_cart': 'Add to Cart',
      'item_added': 'Item added to cart',
      'order_type': 'Order Type',
      'dine_in': 'Dine-In',
      'takeaway': 'Takeaway',
      'delivery': 'Delivery',
      'pickup': 'Pickup',
      'select_table': 'Select Table',
      'select_waiter': 'Select Waiter',
      'no_items_desc': 'No items yet. Tap a menu card to add.',
      'item': 'Item',
      'qty': 'Qty',
      'price': 'Price',
      'split_bill': 'SPLIT BILL',
      'print': 'PRINT',
      'send_to_kitchen': 'SEND TO KITCHEN',
      'add_tip': 'Add Tip',
      'apply_discount': 'Apply Discount',
      'advance_paid': 'Advance Paid',
      'table': 'Table',
      'live_order_feed': 'Live Order Feed',
      'search_orders': 'Search Orders',
      'all': 'All',
      'pending': 'Pending',
      'completed': 'Completed',
      'cancelled': 'Cancelled',
      'manager_dashboard': 'MANAGER DASHBOARD',
      'operational_analytics': 'Operational Analytics',
      'orders_management': 'Orders Management',
      'purchase_management': 'Purchase Management',
      'inventory_management': 'Inventory Management',
      'food_management': 'Food Management',
      'categories': 'Categories',
      'food_items': 'Food Items',
      'production': 'Production',
      'human_resource': 'Human Resource',
      'customer_directory': 'Customer Directory',
      'reports': 'Reports',
      'reservations': 'Reservations',
      'table_qr_codes': 'Table QR Codes',
      'user_management': 'User Management',
      'role_permissions': 'Role & Permissions',
      'security_access': 'Security & Access',
      'active_permissions': 'Active Permissions',
      'system_settings': 'System Settings',
      'configuration': 'Configuration',
      'all_caps': 'ALL',
      'appetizers': 'APPETIZERS',
      'main_course': 'MAIN COURSE',
      'desserts': 'DESSERTS',
      'favorites': 'FAVORITES',
      'recent': 'RECENT',
      'no_orders_in': 'No orders in',
      'order_num_header': 'ORDER #',
      'table_type_header': 'TABLE/TYPE',
      'completed_header': 'COMPLETED',
      'start_time_header': 'START TIME',
      'items_header': 'ITEMS',
      'counter_duration_header': 'COUNTER DURATION',
      'total_duration_header': 'TOTAL DURATION',
      'status_header': 'STATUS',
      'avg_prep_time': 'Avg. Prep Time',
      'avg_counter_time': 'Avg. Counter Time',
      'cancellation_rate': 'Cancellation Rate',
      'orders_in_view': 'Orders in View',
      'detailed_orders_report': 'Detailed Orders Report',
      'website_order': 'Website Order',
      'qr_menu_order': 'QR Menu Order',
      'date_range': 'Date Range',
      'select_date': 'Select Date',
      'select_date_range': 'Select Date Range',
      'select_start_date': 'Select Start Date',
      'select_end_date': 'Select End Date',
      'filter_by_type': 'Filter by Type',
      'filter_by_status': 'Filter by Status',
      'clear_filters': 'Clear Filters',
      'no_results_found': 'No results found',
      'order_velocity_analytics': 'Order Velocity Analytics',
      'lifecycle_tracking': 'Lifecycle tracking from Order to Service',
      'live_bookings': 'Live Bookings',
      'add_new_booking': 'Add New Booking',
      'guests': 'Guests',
      'no_tables_found': 'No tables found',
      'retry_fetch': 'RETRY FETCH',
      'start_new_order': 'Start New Order',
      'manage_active_order': 'Manage Active Order',
      'clear_table': 'Clear Table',
      'manual_status_override': 'Manual Status Override',
      'edit_table_details': 'Edit Table Details',
      'delete_table': 'Delete Table',
      'upcoming': 'Upcoming',
      'confirmed': 'Confirmed',
      'seated': 'Seated',
      'rejected': 'Rejected',
      'available': 'Available',
      'occupied': 'Occupied',
      'reserved': 'Reserved',
      'needs_clearing': 'Needs Clearing',
      'table_number': 'Table Number',
      'capacity': 'Capacity',
      'table_updated': 'Table updated',
      'delete_table_confirm': 'Are you sure you want to remove Table',
      'table_removed': 'Table removed successfully',
      'general': 'General',
      'operations': 'Operations',
      'branding': 'Branding',
      'payments': 'Payments',
      'communications': 'Communications',
      'preparing': 'Preparing',
      'ready': 'Ready',
      'paid': 'Paid',
      'unpaid': 'Unpaid',
      'no_kds_orders': 'No active orders in the kitchen',
      'kitchen_production': 'Kitchen Production',
      'active_tickets': 'active tickets',
      'notification_settings': 'Notification Settings',
      'new_order_received': 'New Order Received',
      'low_stock_alert': 'Low Stock Alert',
      'payment_processed': 'Payment Processed',
      'payment_policy': 'Payment Policy',
      'payment_policy_desc': 'Determine when payment is collected (Pay First for Counter, Pay Last for Tables)',
      'pay_first': 'Pay First',
      'pay_last': 'Pay Last',
      'pay_all': 'Pay All',
      'kitchen_alert': 'Kitchen Alert',
      'system_update': 'System Update',
      'order_ready_pickup': 'Order ready for pickup',
      'order_id': 'Order #',
      'table_label': 'Table',
      'burger_patties_low': 'Burger patties running low',
      'pos_system_updated': 'POS system updated successfully',
      '2_min_ago': '2 min ago',
      '15_min_ago': '15 min ago',
      '1_hour_ago': '1 hour ago',
      '2_hours_ago': '2 hours ago',
      '1_day_ago': '1 day ago',
      'never': 'Never',
      '5_mins': '5 Minutes',
      '15_mins': '15 Minutes',
      '30_mins': '30 Minutes',
      '1_hour': '1 Hour',
      'dark_mode_desc': 'Toggle between light and dark theme',
      'printer_desc': 'Configure receipt printer',
      'sound_desc': 'Enable/disable notification sounds',
      'logout_desc': 'Set automatic logout time',
      'lang_desc': 'Change app language',
      'stock': 'Stock',
      'min': 'Min',
      'unit': 'Unit',
      'save_success': 'Saved successfully',
      'delete_success': 'Deleted successfully',
      'failed_to_load_inventory': 'Failed to load inventory',
      'failed_to_save': 'Failed to save',
      'failed_to_delete': 'Failed to delete',
      'add_new_item': 'Add New Item',
      'edit_item': 'Edit Item',
      'item_name': 'Item Name',
      'current_stock': 'Current Stock',
      'min_stock_level': 'Min Stock Level',
      'save_item': 'Save Item',
      'conn_type': 'Connection Type',
      'printer_ip': 'Printer IP Address',
      'send_test_print': 'Send Test Print',
      'order_notifications': 'Order Notifications',
      'order_notifications_desc': 'Play sound for new orders',
      'notification_volume': 'Notification Volume',
      'select_sound': 'Select Sound',
      'test_sound': 'Test Sound',
      'lang_settings': 'Language Settings',
      'auto_sync_active': 'Auto-sync Active (15s)',
      'live_data_sync': 'Live data synchronization with Online Orders & Reservations',
      'todays_sale': "Today's Sale",
      'todays_orders': "Today's Orders",
      'lifetime_orders': 'Lifetime Orders',
      'total_customers': 'Total Customers',
      'order_service_split': 'Order Service Split',
      'pick_up': 'Pick-up',
      'payment_method_coverage': 'Payment Method Coverage',
      'cash': 'Cash',
      'card_terminal': 'Card/Terminal',
      'online_order': 'Online Order',
      'daily_deductions': 'Daily Deductions/Extras',
      'tips_today': 'Tips (Today)',
      'discounts_label': 'Discounts',
      'pending_orders_kds': 'Pending Orders (KDS)',
      'awaiting_payment': 'Awaiting Payment',
      'today_reservations': 'Today Reservations',
      'active_orders': 'Active Orders',
      'monthly_revenue_trend': 'Monthly Revenue - 6 Month Trend',
      'customize_item': 'Customize',
      'popular_customizations': 'Popular Customizations',
      'uses': 'uses',
      'variant': 'Variant',
      'extras_label': 'Extras',
      'official_receipt': 'Official Receipt',
      'thank_you_visiting': 'THANK YOU FOR VISITING!',
      'print_now': 'PRINT NOW',
      'split_bill_dialog': 'Split Bill',
      'split_by': 'Split by',
      'people': 'people',
      'total_bill': 'Total Bill',
      'each_person': 'Each Person',
      'confirm_split': 'Confirm Split',
      'search_table': 'Search table number...',
      'clear_takeaway': 'Clear / Takeaway',
      'table_number_hint': 'Table Number (e.g. T15)',
      'capacity_seats': 'Capacity (Seats)',
      'add_table': 'ADD TABLE',
      'table_type': 'Table Type',
      'table_size': 'Table Size',
      'chairs_count': 'Chairs #',
      'search_items': 'Search items...',
      'sent_to_printer': 'Sent to Printer...',
      'settings_not_loaded': 'Settings not loaded',
      'retry': 'RETRY',
      'enabled': 'Enabled',
      'disabled': 'Disabled',
      'environment': 'Environment:',
      'test_connection': 'Test Connection',
      'send_test_message': 'Send Test Message',
      'send_test_email_btn': 'Send Test Email',
      'save': 'Save',
      'custom_item': 'Custom Item',
      'capacity_label': 'Capacity',
      'general_settings': 'General Settings',
      'general_settings_desc': 'Configure core restaurant identity and preferences.',
      'restaurant_info': 'Restaurant Information',
      'legal_name': 'Legal Name',
      'legal_name_desc': 'Displayed on receipts and legal docs',
      'primary_currency': 'Primary Currency',
      'primary_currency_desc': 'All financial transactions will use this',
      'interface_theme': 'Interface Theme',
      'interface_theme_desc': 'Visual style for all terminal interfaces',
      'operational_controls': 'Operational Controls',
      'operational_controls_desc': 'Manage taxes, fees, and system automation behavior.',
      'taxes_gratuity': 'Taxes & Gratuity',
      'kitchen_bookings': 'Kitchen & Bookings',
      'order_channels': 'Order Channels',
      'branding_desc': 'Manage your visual identity across POS and Web.',
      'visual_assets': 'Visual Assets',
      'communications_desc': 'Configure WhatsApp, SMS, and Email automation.',
      'communications': 'Communications',
      'twilio_config': 'Twilio Configuration',
      'smtp_config': 'SMTP Configuration',
      'account_sid': 'Account SID',
      'auth_token': 'Auth Token',
      'sender_number': 'Sender Number',
      'smtp_host': 'SMTP Host',
      'smtp_port': 'SMTP Port',
      'smtp_user': 'SMTP Username',
      'smtp_pass': 'SMTP Password',
      'from_email': 'From Email Address',
      'from_name': 'From Name',
      'test_connection': 'Test Connection',
      'test_twilio_msg': 'Testing Twilio Configuration...',
      'test_smtp_msg': 'Testing SMTP Configuration...',
      'test_success': 'Connection Successful!',
      'test_failed': 'Connection Failed',
      'enable_vat': 'Enable VAT/Tax',
      'enable_vat_desc': 'Apply automatic tax calculation to order totals',
      'tax_rate_label': 'Tax Rate (%)',
      'tax_rate_desc': 'Standard percentage for sales tax',
      'default_gratuity': 'Default Gratuity %',
      'default_gratuity_desc': 'Automatic service charge for large groups',
      'kds_timer': 'KDS Warning Timer',
      'kds_timer_desc': 'Minutes before order highlights as delayed',
      'enable_booking_fee': 'Enable Booking Fee',
      'enable_booking_fee_desc': 'Charge customers for advance reservations',
      'booking_fee': 'Booking Fee Amount',
      'booking_fee_amount': 'Booking Fee Amount',
      'booking_fee_amount_desc': 'Fixed fee per reservation',
      'reservations': 'Reservations',
      'qr_table_ordering': 'QR Table Ordering',
      'qr_table_ordering_desc': 'Allow customers to order via QR codes',
      'home_delivery': 'Home Delivery',
      'home_delivery_desc': 'Enable delivery option on website',
      'customer_pickup': 'Customer Pickup',
      'customer_pickup_desc': 'Enable pickup option on website',
      'out_of_stock': 'OUT OF STOCK',
      'clear_btn': 'CLEAR',
      'pay_now': 'PAY NOW',
      'order_updated_success': 'Order updated successfully!',
      'order_placed_success': 'Order placed successfully! Sent to KDS.',
      'server_error_retry': 'Server Error. Please try again.',
      'connection_error_msg': 'Connection Error',
      'table_added_floor': 'Table added to floor plan',
      'select_slot': 'Select Slot',
      'choose_table': 'Choose Table',
      'review_confirm': 'Review & Confirm',
      'visit_time_prompt': 'When would you like to visit?',
      'select_available_table': 'Select an available table',
      'guest_prompt': 'Tell us about the guest',
      'full_name': 'Full Name',
      'whatsapp_phone': 'WhatsApp / Phone',
      'email_address': 'Email Address',
      'special_requests': 'Special Requests / Notes',
      'reservation_summary': 'Reservation Summary',
      'card_details': 'Card Details',
      'powered_by_stripe': 'Powered by Stripe',
      'card_number': 'Card Number',
      'expiry_date': 'Expiry Date',
      'cvc': 'CVC',
      'back_btn': 'BACK',
      'next_btn': 'NEXT',
      'confirm_reservation': 'CONFIRM RESERVATION',
      'please_select_table': 'Please select a table',
      'name_phone_required': 'Name and Phone are required',
      'reservation_success': 'Reservation created successfully!',
      'reservation_failed': 'Failed to create reservation',
      'reject_order': 'Reject Order',
      'rejection_reason_hint': 'e.g., Out of stock, Kitchen too busy...',
      'confirm_rejection': 'CONFIRM REJECTION',
      'reason_required': 'Reason is required',
      'step_label': 'Step',
      'of_label': 'of',
      'no_tables_available': 'No tables available',
      'try_different_date': 'Try a different date or time slot.',
      'pers_label': 'Pers.',
      'date_label': 'Date',
      'time_label': 'Time',
      'guests_label': 'Guests',
      'people_label': 'People',
      'seats_label': 'seats',
      'advance_booking_fee': 'Advance Booking Fee',
      'collect_at_counter': 'Collect from guest at counter',
      'card': 'Card',
      'fee_policy_desc': 'Fee is deductible from final bill but non-refundable for no-shows.',
      'free_status': 'Free',
      'occupied_status': 'Occupied',
      'pax_label': 'pax',
      'link_copied_for': 'Link copied for',
      'copy_link': 'Copy Link',
      'settings_updated_msg': 'Settings updated successfully!',
      'messaging_integration': 'Messaging Integration',
      'twilio_setup_desc': 'Configure Twilio for WhatsApp and SMS notifications.',
      'account_sid': 'Account SID',
      'auth_token': 'Auth Token',
      'sender_number': 'Sender Number',
      'waba_id': 'WABA ID (Business Account ID)',
      'test_msg_desc': 'Enter a phone number to send a test message.',
      'test_phone_number': 'Test Phone Number',
      'sending_test_msg': 'Sending test message to',
      'test_msg_success': 'Success! Test message sent.',
      'error_label': 'Error',
      'email_notifications': 'Email & Notifications',
      'smtp_setup_desc': 'Configure your SMTP server to send automated emails.',
      'smtp_host': 'SMTP Host',
      'smtp_port': 'SMTP Port',
      'username': 'Username',
      'password': 'Password',
      'from_email': 'From Email',
      'from_name': 'From Name',
      'test_email_desc': 'Enter an email address to send a test message.',
      'test_email_address': 'Test Email Address',
      'sending_test_email': 'Sending test email to',
      'test_email_success': 'Success! Test email sent.',
      'order_marked_status': 'Order marked as',
      'failed_update_status': 'Failed to update status',
      'item_removed_order': 'Item removed from order.',
      'category_created_success': 'Category created successfully',
      'category_failed_create': 'Failed to create category',
      'category_updated_success': 'Category updated successfully',
      'category_deleted_success': 'Category deleted successfully',
      'menu_item_created_success': 'Menu item created successfully',
      'menu_item_updated_success': 'Menu item updated successfully',
      'menu_item_deleted_success': 'Menu item deleted successfully',
      'setting_updated_success': 'Setting updated successfully',
      'user_created_success': 'User created successfully',
      'user_updated_success': 'User updated successfully',
      'user_deleted_success': 'User deleted successfully',
      'customer_added_success': 'Customer added successfully',
      'customer_updated_success': 'Customer updated successfully',
      'customer_deleted_success': 'Customer deleted successfully',
      'error_adding_customer': 'Error adding customer',
      'error_updating_customer': 'Error updating customer',
      'error_deleting_customer': 'Error deleting customer',
      'permissions_updated': 'Permissions updated',
      'date_btn': 'DATE',
      'time_btn': 'TIME',
      'guests_btn': 'GUESTS',
      'coming_soon': 'Coming Soon',
      'back_to_dashboard': 'BACK TO DASHBOARD',
      'error_details': 'Error Details',
      'show_details': 'SHOW DETAILS',
      'staff_management': 'Staff Management',
      'staff_mgmt_desc': 'Manage your restaurant team and access levels',
      'add_new_staff': 'ADD NEW STAFF',
      'no_users_found': 'No users found.',
      'roles_permissions_title': 'Roles & Permissions',
      'roles_desc': 'Configure access levels for each job role',
      'edit_permissions_btn': 'EDIT PERMISSIONS',
      'assign_role': 'Assign Role',
      'delete_staff_q': 'Delete Staff?',
      'remove_user_confirm': 'Are you sure you want to remove user from the system?',
      'business_intelligence': 'Business Intelligence',
      'no_data': 'No data',
      'error_loading_page': 'Oops! Something went wrong loading this page.',
      'close_btn': 'Close',
      'edit_staff_details': 'Edit Staff Details',
      'first_name': 'First Name',
      'last_name': 'Last Name',
      'email_label': 'Email',
      'phone_label': 'Phone',
      'cancel_btn': 'CANCEL',
      'create_btn': 'CREATE',
      'save_btn': 'SAVE',
      'delete_btn': 'DELETE',
      'summary_tab': 'SUMMARY',
      'sales_log_tab': 'SALES LOG',
      'product_mix_tab': 'PRODUCT MIX',
      'staff_tab': 'STAFF',
      'net_sales': 'NET SALES',
      'total_orders': 'TOTAL ORDERS',
      'avg_order': 'AVG. ORDER',
      'est_profit': 'EST. PROFIT',
      'operational_status': 'Operational Status',
      'top_selling_items': 'Top Selling Items (30 Days)',
      'recent_transactions': 'Recent Transactions',
      'id_col': 'ID',
      'time_col': 'TIME',
      'type_col': 'TYPE',
      'total_col': 'TOTAL',
      'status_col': 'STATUS',
      'no_sales_data': 'No sales data',
      'no_shift_data': 'No shift data available for today',
      'shift_label': 'Shift',
      'back_to_analytics': 'BACK TO ANALYTICS',
      'clock_in_out': 'Clock In/Out',
      'recent_activity': 'Recent Activity',
      'staff_online': 'Staff Online',
      'quick_clock_in_test': 'Quick Clock-In for testing',
      'clock_in_test': 'Clock In (John Staff)',
      'messages_inquiries': 'Messages & Inquiries',
      'no_messages_yet': 'No messages yet',
      'mark_as_read': 'Mark as Read',
      'print_all_qr': 'Print All QR Codes',
      'version_label': 'Version',
      'primary_logo_upload': 'Primary Logo Upload',
      'main_brand_logo_desc': 'Main brand logo shown in the header',
      'secondary_logo_upload': 'Secondary Logo Upload',
      'secondary_branding_desc': 'Secondary branding (e.g. Halal logo)',
      'environment_label': 'Environment',
      'waiting_status': 'Waiting',
      'edit_permissions_title': 'Edit Permissions',
      'received_at': 'Received at',
      'from_label': 'From',
      'system_reset': 'System Reset',
      'system_maintenance': 'System Maintenance',
      'reset_transactional_data_desc': 'Perform administrative maintenance by purging transactional records while keeping structural data intact.',
      'danger_zone': 'Danger Zone',
      'reset_warning_text': 'This action will permanently delete all orders, payments, and operational history. This cannot be undone.',
      'data_impact_analysis': 'Data Impact Analysis',
      'orders_payments_reservations': 'Orders, Payments & Reservations',
      'expenses_purchases': 'Expenses & Purchase Orders',
      'menu_items_categories': 'Menu Items & Categories',
      'users_roles_permissions': 'Users, Roles & Permissions',
      'table_layouts_settings': 'Table Layouts & Settings',
      'reset_transactional_data': 'Reset Transactional Data',
      'will_be_deleted': 'WILL BE DELETED',
      'will_be_preserved': 'WILL BE PRESERVED',
      'are_you_sure': 'Are you absolutely sure?',
      'reset_confirmation_detailed': 'You are about to purge all transactional data from the system. This will reset your dashboard metrics and order history to zero. Master data like your menu and staff will remain untouched.',
      'confirm_reset': 'CONFIRM RESET',
      'transactional_reset_success': 'Transactional data has been successfully reset.',
      'payment_success_message': 'Payment processed successfully!',
      'order_payment': 'Order Payment',
      'amount_due': 'Amount Due',
      'confirm_payment': 'CONFIRM PAYMENT',
      'complete_payment': 'COMPLETE PAYMENT',
      'checkout_btn': 'CHECKOUT',
    },
    'Arabic': {
      'dashboard': 'لوحة القيادة',
      'kds': 'نظام شاشة المطبخ',
      'reservation': 'الحجز',
      'orders': 'الطلبات',
      'tables': 'الطاولات',
      'pos': 'نقطة البيع',
      'waiting': 'انتظار',
      'settings': 'الإعدادات',
      'dark_mode': 'الوضع المظلم',
      'printer_settings': 'إعدادات الطابعة',
      'sound_settings': 'إعدادات الصوت',
      'auto_logout': 'تسجيل الخروج التلقائي',
      'language': 'اللغة',
      'mission_control': 'مركز التحكم',
      'terminal': 'المحطة',
      'close': 'إغلاق',
      'attention': 'تنبيه',
      'add_items_to_cart_warning': 'يرجى إضافة أصناف إلى السلة قبل المتابعة.',
      'select_table_warning': 'يرجى اختيار طاولة لهذا الطلب.',
      'select_waiter_warning': 'يرجى اختيار نادل لهذا الطلب.',
      'enter_guest_name_warning': 'يرجى إدخال اسم الضيف.',
      'enter_guest_phone_warning': 'يرجى إدخال رقم هاتف الضيف.',
      'enter_table_number_warning': 'يرجى إدخال رقم الطاولة.',
      'enter_capacity_warning': 'يرجى تحديد سعة الطاولة.',
      'fill_guest_details_warning': 'يرجى تقديم الاسم ورقم الهاتف للمتابعة.',
      'ok': 'موافق',
      'save_settings': 'حفظ الإعدادات',
      'save_changes': 'حفظ التغييرات',
      'cancel': 'إلغاء',
      'mark_all_read': 'تحديد الكل كمقروء',
      'user_profile': 'ملف المستخدم',
      'terminal_id': 'المحطة #',
      'role_admin': 'الدور: مدير',
      'logout_not_connected': 'وظيفة تسجيل الخروج غير متصلة',
      'provide_rejection_reason': 'يرجى تقديم سبب لرفض الطلب',
      'network': 'الشبكة',
      'bluetooth': 'بلوتوث',
      'usb': 'USB',
      'test_print_sent': 'تم إرسال طباعة تجريبية!',
      'invalid_ip_format': 'تنسيق عنوان IP غير صالح',
      'notifications': 'التنبيهات',
      'main_course_items': 'الأطباق الرئيسية',
      'updating_order': 'تحديث الطلب',
      'demo_mode_desc': 'وضع العرض: عرض عينات من الأطباق المميزة',
      'browse_menu_desc': 'تصفح قائمة الطعام وأضفها إلى الطلب الحالي',
      'cancel_edit': 'إلغاء التعديل',
      'all_items': 'كل الأصناف',
      'cart_details': 'تفاصيل السلة',
      'empty_cart': 'سلة التسوق فارغة',
      'checkout': 'الدفع',
      'total': 'المجموع',
      'subtotal': 'المجموع الفرعي',
      'tax': 'الضريبة',
      'discount': 'الخصم',
      'tip': 'بخشيش',
      'add_to_cart': 'أضف إلى السلة',
      'item_added': 'تمت إضافة الصنف إلى السلة',
      'order_type': 'نوع الطلب',
      'dine_in': 'تناول هنا',
      'takeaway': 'سفري',
      'delivery': 'توصيل',
      'pickup': 'استلام',
      'select_table': 'اختر الطاولة',
      'select_waiter': 'اختر النادل',
      'no_items_desc': 'لا توجد أصناف بعد. اضغط على بطاقة القائمة للإضافة.',
      'item': 'الصنف',
      'qty': 'الكمية',
      'price': 'السعر',
      'split_bill': 'تقسيم الفاتورة',
      'print': 'طباعة',
      'send_to_kitchen': 'إرسال للمطبخ',
      'add_tip': 'إضافة بخشيش',
      'apply_discount': 'تطبيق الخصم',
      'advance_paid': 'مقدم مدفوع',
      'table': 'طاولة',
      'live_order_feed': 'تغذية الطلبات الحية',
      'search_orders': 'البحث في الطلبات',
      'all': 'الكل',
      'pending': 'قيد الانتظار',
      'completed': 'مكتمل',
      'cancelled': 'ملغي',
      'manager_dashboard': 'لوحة تحكم المدير',
      'operational_analytics': 'التحليلات التشغيلية',
      'orders_management': 'إدارة الطلبات',
      'purchase_management': 'إدارة المشتريات',
      'inventory_management': 'إدارة المخزون',
      'food_management': 'إدارة الطعام',
      'categories': 'الفئات',
      'food_items': 'أصناف الطعام',
      'production': 'الإنتاج',
      'avg_prep_time': 'متوسط وقت التحضير',
      'avg_counter_time': 'متوسط الوقت عند الكاونتر',
      'cancellation_rate': 'معدل الإلغاء',
      'orders_in_view': 'الطلبات المعروضة',
      'detailed_orders_report': 'تقرير الطلبات المفصل',
      'website_order': 'طلب الموقع',
      'qr_menu_order': 'طلب قائمة QR',
      'date_range': 'نطاق التاريخ',
      'select_date': 'اختر التاريخ',
      'select_date_range': 'اختر نطاق التاريخ',
      'select_start_date': 'اختر تاريخ البدء',
      'select_end_date': 'اختر تاريخ الانتهاء',
      'filter_by_type': 'تصفية حسب النوع',
      'filter_by_status': 'تصفية حسب الحالة',
      'clear_filters': 'مسح التصفية',
      'no_results_found': 'لم يتم العثور على نتائج',
      'human_resource': 'الموارد البشرية',
      'customer_directory': 'دليل العملاء',
      'reports': 'التقارير',
      'reservations': 'الحجوزات',
      'table_qr_codes': 'رموز QR للطاولات',
      'user_management': 'إدارة المستخدمين',
      'role_permissions': 'الأدوار والأذونات',
      'security_access': 'الأمن والوصول',
      'active_permissions': 'الأذونات النشطة',
      'system_settings': 'إعدادات النظام',
      'configuration': 'إعداد',
      'all_caps': 'الكل',
      'appetizers': 'مقبلات',
      'main_course': 'طبق رئيسي',
      'desserts': 'حلويات',
      'favorites': 'المفضلة',
      'recent': 'الأخيرة',
      'no_orders_in': 'لا توجد طلبات في حالة',
      'order_num_header': 'رقم الطلب #',
      'table_type_header': 'الطاولة/النوع',
      'completed_header': 'مكتمل',
      'start_time_header': 'وقت البدء',
      'items_header': 'الأصناف',
      'counter_duration_header': 'مدة الكاونتر',
      'total_duration_header': 'المدة الإجمالية',
      'status_header': 'الحالة',
      'order_velocity_analytics': 'تحليلات سرعة الطلب',
      'lifecycle_tracking': 'تتبع دورة الحياة من الطلب إلى الخدمة',
      'live_bookings': 'الحجوزات المباشرة',
      'add_new_booking': 'إضافة حجز جديد',
      'guests': 'ضيوف',
      'select_booking_details': 'اختر حجزًا لعرض التفاصيل',
      'select_order_details': 'اختر طلبًا لعرض التفاصيل',
      'interactive_floor_plan': 'خريطة الطوابق التفاعلية',
      'add_new_table': 'إضافة طاولة جديدة',
      'no_tables_found': 'لم يتم العثور على طاولات',
      'retry_fetch': 'إعادة المحاولة',
      'start_new_order': 'بدء طلب جديد',
      'manage_active_order': 'إدارة الطلب النشط',
      'clear_table': 'تفريغ الطاولة',
      'manual_status_override': 'تجاوز الحالة يدويًا',
      'edit_table_details': 'تعديل تفاصيل الطاولة',
      'delete_table': 'حذف الطاولة',
      'upcoming': 'قادم',
      'confirmed': 'مؤكد',
      'seated': 'جالس',
      'rejected': 'مرفوض',
      'available': 'متاح',
      'occupied': 'مشغول',
      'reserved': 'محجوز',
      'needs_clearing': 'بحاجة لتنظيف',
      'table_number': 'رقم الطاولة',
      'capacity': 'السعة',
      'table_updated': 'تم تحديث الطاولة',
      'delete_table_confirm': 'هل أنت متأكد أنك تريد إزالة الطاولة',
      'table_removed': 'تمت إزالة الطاولة بنجاح',
      'general': 'عام',
      'operations': 'عمليات',
      'branding': 'العلامة التجارية',
      'payments': 'مدفوعات',
      'communications': 'اتصالات',
      'preparing': 'قيد التحضير',
      'ready': 'جاهز',
      'paid': 'مدفوع',
      'unpaid': 'غير مدفوع',
      'no_kds_orders': 'لا توجد طلبات نشطة في المطبخ',
      'kitchen_production': 'إنتاج المطبخ',
      'active_tickets': 'تذاكر نشطة',
      'notification_settings': 'إعدادات التنبيهات',
      'new_order_received': 'تم استلام طلب جديد',
      'low_stock_alert': 'تنبيه انخفاض المخزون',
      'payment_processed': 'تمت معالجة الدفع',
      'payment_policy': 'سياسة الدفع',
      'payment_policy_desc': 'تحديد وقت تحصيل الدفع (الدفع أولاً للكاونتر، الدفع آخراً للطاولات)',
      'pay_first': 'دفع أولاً',
      'pay_last': 'دفع آخراً',
      'pay_all': 'دفع الكل',
      'kitchen_alert': 'تنبيه المطبخ',
      'system_update': 'تحديث النظام',
      'order_ready_pickup': 'الطلب جاهز للاستلام',
      'order_id': 'رقم الطلب #',
      'table_label': 'طاولة',
      'burger_patties_low': 'فطائر البرجر بدأت تنفد',
      'pos_system_updated': 'تم تحديث نظام نقطة البيع بنجاح',
      '2_min_ago': 'منذ دقيقتين',
      '15_min_ago': 'منذ 15 دقيقة',
      '1_hour_ago': 'منذ ساعة',
      '2_hours_ago': 'منذ ساعتين',
      '1_day_ago': 'منذ يوم',
      'never': 'أبداً',
      '5_mins': '5 دقائق',
      '15_mins': '15 دقيقة',
      '30_mins': '30 دقيقة',
      '1_hour': 'ساعة واحدة',
      'dark_mode_desc': 'التبديل بين الوضع المظلم والمضيء',
      'printer_desc': 'تكوين طابعة الفواتير',
      'sound_desc': 'تفعيل/تعطيل أصوات التنبيه',
      'logout_desc': 'ضبط وقت تسجيل الخروج التلقائي',
      'lang_desc': 'تغيير لغة التطبيق',
      'stock': 'المخزون',
      'min': 'الحد الأدنى',
      'unit': 'الوحدة',
      'save_success': 'تم الحفظ بنجاح',
      'delete_success': 'تم الحذف بنجاح',
      'failed_to_load_inventory': 'فشل في تحميل المخزون',
      'failed_to_save': 'فشل في الحفظ',
      'failed_to_delete': 'فشل في الحذف',
      'add_new_item': 'إضافة عنصر جديد',
      'edit_item': 'تعديل العنصر',
      'item_name': 'اسم العنصر',
      'current_stock': 'المخزون الحالي',
      'min_stock_level': 'مستوى الحد الأدنى',
      'save_item': 'حفظ العنصر',
      'conn_type': 'نوع الاتصال',
      'printer_ip': 'عنوان IP للطابعة',
      'send_test_print': 'إرسال طباعة تجريبية',
      'order_notifications': 'تنبيهات الطلبات',
      'order_notifications_desc': 'تشغيل صوت عند وصول طلب جديد',
      'notification_volume': 'مستوى صوت التنبيه',
      'select_sound': 'اختر الصوت',
      'test_sound': 'تجربة الصوت',
      'lang_settings': 'إعدادات اللغة',
      'auto_sync_active': 'المزامنة التلقائية نشطة (15 ث)',
      'live_data_sync': 'مزامنة البيانات الحية مع الطلبات عبر الإنترنت والحجوزات',
      'todays_sale': 'مبيعات اليوم',
      'todays_orders': 'طلبات اليوم',
      'lifetime_orders': 'إجمالي الطلبات',
      'total_customers': 'إجمالي العملاء',
      'order_service_split': 'توزيع نوع الخدمة',
      'pick_up': 'استلام',
      'payment_method_coverage': 'تغطية طريقة الدفع',
      'cash': 'نقدي',
      'card_terminal': 'بطاقة/جهاز',
      'online_order': 'طلب إلكتروني',
      'daily_deductions': 'الخصومات/الإضافات اليومية',
      'tips_today': 'البخشيش (اليوم)',
      'discounts_label': 'خصومات',
      'pending_orders_kds': 'الطلبات قيد الانتظار (KDS)',
      'awaiting_payment': 'في انتظار الدفع',
      'today_reservations': 'حجوزات اليوم',
      'active_orders': 'الطلبات النشطة',
      'monthly_revenue_trend': 'الإيرادات الشهرية - اتجاه 6 أشهر',
      'customize_item': 'تخصيص',
      'popular_customizations': 'الإضافات الأكثر شعبية',
      'uses': 'استخدامات',
      'variant': 'نوع',
      'extras_label': 'إضافات',
      'official_receipt': 'إيصال رسمي',
      'thank_you_visiting': 'شكراً لزيارتكم!',
      'print_now': 'طباعة الآن',
      'split_bill_dialog': 'تقسيم الفاتورة',
      'split_by': 'تقسيم على',
      'people': 'أشخاص',
      'total_bill': 'إجمالي الفاتورة',
      'each_person': 'لكل شخص',
      'confirm_split': 'تأكيد التقسيم',
      'search_table': 'ابحث عن رقم الطاولة...',
      'clear_takeaway': 'إلغاء / سفري',
      'table_number_hint': 'رقم الطاولة (مثال: T15)',
      'capacity_seats': 'السعة (مقاعد)',
      'add_table': 'إضافة طاولة',
      'table_type': 'نوع الطاولة',
      'table_size': 'حجم الطاولة',
      'chairs_count': 'عدد الكراسي #',
      'search_items': 'ابحث عن أصناف...',
      'sent_to_printer': 'تم الإرسال للطابعة...',
      'settings_not_loaded': 'لم يتم تحميل الإعدادات',
      'retry': 'إعادة المحاولة',
      'enabled': 'مفعّل',
      'disabled': 'معطّل',
      'environment': 'البيئة:',
      'test_connection': 'اختبار الاتصال',
      'send_test_message': 'إرسال رسالة تجريبية',
      'send_test_email_btn': 'إرسال بريد تجريبي',
      'save': 'حفظ',
      'custom_item': 'صنف مخصص',
      'capacity_label': 'السعة',
      'general_settings': 'الإعدادات العامة',
      'general_settings_desc': 'تكوين هوية المطعم والتفضيلات الأساسية.',
      'restaurant_info': 'معلومات المطعم',
      'legal_name': 'الاسم القانوني',
      'legal_name_desc': 'يظهر على الإيصالات والمستندات القانونية',
      'primary_currency': 'العملة الرئيسية',
      'primary_currency_desc': 'جميع المعاملات المالية ستستخدم هذه',
      'interface_theme': 'سمة الواجهة',
      'interface_theme_desc': 'النمط البصري لجميع واجهات الطرفية',
      'operational_controls': 'الضبط التشغيلي',
      'operational_controls_desc': 'إدارة الضرائب والرسوم وسلوك الأتمتة.',
      'taxes_gratuity': 'الضرائب والبخشيش',
      'kitchen_bookings': 'المطبخ والحجوزات',
      'order_channels': 'قنوات الطلب',
      'branding_desc': 'إدارة هويتك البصرية عبر POS والويب.',
      'visual_assets': 'الأصول البصرية',
      'communications_desc': 'تكوين واتساب والرسائل والبريد الإلكتروني.',
      'enable_vat': 'تفعيل ضريبة القيمة المضافة',
      'enable_vat_desc': 'تطبيق حساب الضريبة التلقائي على إجمالي الطلبات',
      'tax_rate_label': 'معدل الضريبة (%)',
      'tax_rate_desc': 'النسبة المئوية القياسية لضريبة المبيعات',
      'default_gratuity': 'نسبة البخشيش الافتراضية %',
      'default_gratuity_desc': 'رسوم خدمة تلقائية للمجموعات الكبيرة',
      'kds_timer': 'مؤقت تحذير KDS',
      'kds_timer_desc': 'دقائق قبل تمييز الطلب كمتأخر',
      'enable_booking_fee': 'تفعيل رسوم الحجز',
      'enable_booking_fee_desc': 'تحصيل رسوم من العملاء للحجوزات المسبقة',
      'booking_fee_amount': 'مبلغ رسوم الحجز',
      'booking_fee_amount_desc': 'رسوم ثابتة لكل حجز',
      'qr_table_ordering': 'طلب طاولة QR',
      'qr_table_ordering_desc': 'السماح للعملاء بالطلب عبر رموز QR',
      'home_delivery': 'توصيل منزلي',
      'home_delivery_desc': 'تفعيل خيار التوصيل على الموقع الإلكتروني',
      'customer_pickup': 'استلام العميل',
      'customer_pickup_desc': 'تفعيل خيار الاستلام على الموقع الإلكتروني',
      'out_of_stock': 'نفذ من المخزون',
      'clear_btn': 'مسح',
      'pay_now': 'ادفع الآن',
      'order_updated_success': 'تم تحديث الطلب بنجاح!',
      'order_placed_success': 'تم تقديم الطلب بنجاح! أرسل إلى KDS.',
      'server_error_retry': 'خطأ في الخادم. يرجى المحاولة مرة أخرى.',
      'connection_error_msg': 'خطأ في الاتصال',
      'table_added_floor': 'تمت إضافة الطاولة إلى مخطط الأرضية',
      'select_slot': 'اختر موعداً',
      'choose_table': 'اختر طاولة',
      'review_confirm': 'المراجعة والتأكيد',
      'visit_time_prompt': 'متى تود زيارتنا؟',
      'select_available_table': 'اختر طاولة متاحة',
      'guest_prompt': 'أخبرنا عن الضيف',
      'full_name': 'الاسم الكامل',
      'whatsapp_phone': 'واتساب / الهاتف',
      'email_address': 'البريد الإلكتروني',
      'special_requests': 'طلبات خاصة / ملاحظات',
      'reservation_summary': 'ملخص الحجز',
      'card_details': 'تفاصيل البطاقة',
      'powered_by_stripe': 'بدعم من Stripe',
      'card_number': 'رقم البطاقة',
      'expiry_date': 'تاريخ الانتهاء',
      'cvc': 'CVC',
      'back_btn': 'رجوع',
      'next_btn': 'التالي',
      'confirm_reservation': 'تأكيد الحجز',
      'please_select_table': 'يرجى اختيار طاولة',
      'name_phone_required': 'الاسم والهاتف مطلوبان',
      'reservation_success': 'تم إنشاء الحجز بنجاح!',
      'reservation_failed': 'فشل في إنشاء الحجز',
      'reject_order': 'رفض الطلب',
      'rejection_reason_hint': 'مثال: نفذ من المخزون، المطبخ مشغول جداً...',
      'confirm_rejection': 'تأكيد الرفض',
      'reason_required': 'السبب مطلوب',
      'step_label': 'خطوة',
      'of_label': 'من',
      'no_tables_available': 'لا توجد طاولات متاحة',
      'try_different_date': 'جرب تاريخاً أو وقتاً مختلفاً.',
      'pers_label': 'شخص',
      'date_label': 'التاريخ',
      'time_label': 'الوقت',
      'guests_label': 'الضيوف',
      'people_label': 'أشخاص',
      'seats_label': 'مقاعد',
      'advance_booking_fee': 'رسوم الحجز المسبق',
      'collect_at_counter': 'تحصل من الضيف عند الكاونتر',
      'card': 'بطاقة',
      'fee_policy_desc': 'الرسوم قابلة للخصم من الفاتورة النهائية ولكن غير قابلة للاسترداد في حالة عدم الحضور.',
      'free_status': 'شاغر',
      'occupied_status': 'مشغول',
      'pax_label': 'شخص',
      'link_copied_for': 'تم نسخ الرابط لـ',
      'copy_link': 'نسخ الرابط',
      'settings_updated_msg': 'تم تحديث الإعدادات بنجاح!',
      'messaging_integration': 'تكامل المراسلة',
      'twilio_setup_desc': 'تكوين Twilio لتنبيهات واتساب والرسائل النصية.',
      'account_sid': 'Account SID',
      'auth_token': 'Auth Token',
      'sender_number': 'رقم المرسل',
      'waba_id': 'WABA ID',
      'test_msg_desc': 'أدخل رقم الهاتف لإرسال رسالة تجريبية.',
      'test_phone_number': 'رقم الهاتف التجريبي',
      'sending_test_msg': 'جاري إرسال رسالة تجريبية إلى',
      'test_msg_success': 'تم! تم إرسال الرسالة التجريبية.',
      'error_label': 'خطأ',
      'email_notifications': 'البريد الإلكتروني والتنبيهات',
      'smtp_setup_desc': 'تكوين خادم SMTP الخاص بك لإرسال رسائل البريد الإلكتروني التلقائية.',
      'smtp_host': 'SMTP Host',
      'smtp_port': 'SMTP Port',
      'username': 'اسم المستخدم',
      'password': 'كلمة المرور',
      'from_email': 'من البريد الإلكتروني',
      'from_name': 'اسم المرسل',
      'test_email_desc': 'أدخل عنوان البريد الإلكتروني لإرسال رسالة تجريبية.',
      'test_email_address': 'عنوان البريد التجريبي',
      'sending_test_email': 'جاري إرسال بريد تجريبي إلى',
      'test_email_success': 'تم! تم إرسال البريد التجريبي.',
      'order_marked_status': 'تم تمييز الطلب كـ',
      'failed_update_status': 'فشل تحديث الحالة',
      'item_removed_order': 'تمت إزالة الصنف من الطلب.',
      'category_created_success': 'تم إنشاء الفئة بنجاح',
      'category_failed_create': 'فشل في إنشاء الفئة',
      'category_updated_success': 'تم تحديث الفئة بنجاح',
      'category_deleted_success': 'تم حذف الفئة بنجاح',
      'menu_item_created_success': 'تم إنشاء صنف القائمة بنجاح',
      'menu_item_updated_success': 'تم تحديث صنف القائمة بنجاح',
      'menu_item_deleted_success': 'تم حذف صنف القائمة بنجاح',
      'setting_updated_success': 'تم تحديث الإعداد بنجاح',
      'user_created_success': 'تم إنشاء المستخدم بنجاح',
      'user_updated_success': 'تم تحديث المستخدم بنجاح',
      'user_deleted_success': 'تم حذف المستخدم بنجاح',
      'permissions_updated': 'تم تحديث الأذونات',
      'date_btn': 'التاريخ',
      'time_btn': 'الوقت',
      'guests_btn': 'الضيوف',
      'coming_soon': 'قريباً',
      'back_to_dashboard': 'العودة إلى لوحة القيادة',
      'error_details': 'تفاصيل الخطأ',
      'show_details': 'عرض التفاصيل',
      'staff_management': 'إدارة الموظفين',
      'staff_mgmt_desc': 'إدارة فريق المطعم ومستويات الوصول',
      'add_new_staff': 'إضافة موظف جديد',
      'no_users_found': 'لم يتم العثور على مستخدمين.',
      'roles_permissions_title': 'الأدوار والأذونات',
      'roles_desc': 'تكوين مستويات الوصول لكل دور وظيفي',
      'edit_permissions_btn': 'تعديل الأذونات',
      'assign_role': 'تعيين دور',
      'delete_staff_q': 'حذف موظف؟',
      'remove_user_confirm': 'هل أنت متأكد أنك تريد إزالة المستخدم من النظام؟',
      'business_intelligence': 'ذكاء الأعمال',
      'no_data': 'لا توجد بيانات',
      'error_loading_page': 'عذراً! حدث خطأ ما أثناء تحميل هذه الصفحة.',
      'close_btn': 'إغلاق',
      'edit_staff_details': 'تعديل تفاصيل الموظف',
      'first_name': 'الاسم الأول',
      'last_name': 'اسم العائلة',
      'email_label': 'البريد الإلكتروني',
      'phone_label': 'الهاتف',
      'cancel_btn': 'إلغاء',
      'create_btn': 'إنشاء',
      'save_btn': 'حفظ',
      'delete_btn': 'حذف',
      'summary_tab': 'الملخص',
      'sales_log_tab': 'سجل المبيعات',
      'product_mix_tab': 'مزيج المنتجات',
      'staff_tab': 'الموظفين',
      'net_sales': 'صافي المبيعات',
      'total_orders': 'إجمالي الطلبات',
      'avg_order': 'متوسط الطلب',
      'est_profit': 'الربح التقديري',
      'operational_status': 'الحالة التشغيلية',
      'top_selling_items': 'الأصناف الأكثر مبيعاً (30 يوماً)',
      'recent_transactions': 'المعاملات الأخيرة',
      'id_col': 'المعرف',
      'time_col': 'الوقت',
      'type_col': 'النوع',
      'total_col': 'الإجمالي',
      'status_col': 'الحالة',
      'no_sales_data': 'لا توجد بيانات مبيعات',
      'no_shift_data': 'لا توجد بيانات ورديات متاحة لليوم',
      'shift_label': 'الوردية',
      'back_to_analytics': 'العودة إلى التحليلات',
      'clock_in_out': 'تسجيل الحضور/الانصراف',
      'recent_activity': 'النشاط الأخير',
      'staff_online': 'الموظفون المتصلون',
      'quick_clock_in_test': 'تسجيل دخول سريع للاختبار',
      'clock_in_test': 'تسجيل دخول (موظف تجريبي)',
      'messages_inquiries': 'الرسائل والاستفسارات',
      'no_messages_yet': 'لا توجد رسائل بعد',
      'mark_as_read': 'تمييز كمقروء',
      'print_all_qr': 'طباعة جميع رموز QR',
      'version_label': 'الإصدار',
      'primary_logo_upload': 'تحميل الشعار الرئيسي',
      'main_brand_logo_desc': 'شعار العلامة التجارية الرئيسي المعروض في الرأس',
      'secondary_logo_upload': 'تحميل الشعار الثانوي',
      'secondary_branding_desc': 'العلامة التجارية الثانوية (مثلاً شعار حلال)',
      'environment_label': 'البيئة',
      'waiting_status': 'في الانتظار',
      'edit_permissions_title': 'تعديل الأذونات',
      'received_at': 'تم الاستلام في',
      'from_label': 'من',
      'system_reset': 'إعادة ضبط النظام',
      'system_maintenance': 'صيانة النظام',
      'reset_transactional_data_desc': 'إجراء صيانة إدارية عن طريق مسح السجلات المعاملات مع الحفاظ على البيانات الهيكلية سليمة.',
      'danger_zone': 'منطقة الخطر',
      'reset_warning_text': 'سيؤدي هذا الإجراء إلى حذف جميع الطلبات والمدفوعات والسجل التشغيلي بشكل نهائي. لا يمكن التراجع عن هذا الإجراء.',
      'data_impact_analysis': 'تحليل تأثير البيانات',
      'orders_payments_reservations': 'الطلبات والمدفوعات والحجوزات',
      'expenses_purchases': 'المصاريف وطلبات الشراء',
      'menu_items_categories': 'أصناف القائمة والفئات',
      'users_roles_permissions': 'المستخدمون والأدوار والأذونات',
      'table_layouts_settings': 'تخطيطات الطاولات والإعدادات',
      'reset_transactional_data': 'إعادة ضبط بيانات المعاملات',
      'will_be_deleted': 'سيتم حذفها',
      'will_be_preserved': 'سيتم الحفاظ عليها',
      'are_you_sure': 'هل أنت متأكد تماماً؟',
      'reset_confirmation_detailed': 'أنت على وشك مسح جميع بيانات المعاملات من النظام. سيؤدي هذا إلى إعادة تعيين مقاييس لوحة القيادة وسجل الطلبات إلى الصفر. ستبقى البيانات الأساسية مثل قائمتك وموظفيك دون تغيير.',
      'confirm_reset': 'تأكيد إعادة الضبط',
      'transactional_reset_success': 'تمت إعادة ضبط بيانات المعاملات بنجاح.',
      'payment_success_message': 'تمت معالجة الدفع بنجاح!',
      'order_payment': 'دفع الطلب',
      'amount_due': 'المبلغ المستحق',
      'confirm_payment': 'تأكيد الدفع',
      'complete_payment': 'إكمال الدفع',
      'checkout_btn': 'الدفع',
    },
    'Urdu': {
      'dashboard': 'ڈیش بورڈ',
      'kds': 'کچن ڈسپلے سسٹم',
      'reservation': 'ریزرویشن',
      'orders': 'آرڈرز',
      'tables': 'ٹیبلز',
      'pos': 'پی او ایس',
      'waiting': 'انتظار',
      'settings': 'ترتیبات',
      'dark_mode': 'ڈارک موڈ',
      'printer_settings': 'پرنٹر کی ترتیبات',
      'sound_settings': 'آواز کی ترتیبات',
      'auto_logout': 'آٹو لاگ آؤٹ',
      'language': 'زبان',
      'mission_control': 'مشن کنٹرول',
      'terminal': 'ٹرمینل',
      'close': 'بند کریں',
      'save_settings': 'ترتیبات محفوظ کریں',
      'save_changes': 'تبدیلیاں محفوظ کریں',
      'cancel': 'منسوخ کریں',
      'mark_all_read': 'تمام پڑھے ہوئے نشان زد کریں',
      'user_profile': 'صارف کا پروفائل',
      'terminal_id': 'ٹرمینل #',
      'role_admin': 'کردار: ایڈمنسٹریٹر',
      'logout_not_connected': 'لاگ آؤٹ کی فعالیت منسلک نہیں ہے',
      'provide_rejection_reason': 'براہ کرم آرڈر مسترد کرنے کی وجہ بتائیں',
      'network': 'نیٹ ورک',
      'bluetooth': 'بلوٹوتھ',
      'usb': 'USB',
      'test_print_sent': 'ٹیسٹ پرنٹ بھیج دیا گیا!',
      'invalid_ip_format': 'آئی پی ایڈریس فارمیٹ درست نہیں ہے',
      'notifications': 'اطلاعات',
      'main_course_items': 'مین کورس آئٹمز',
      'updating_order': 'آرڈر اپ ڈیٹ کر رہا ہے',
      'demo_mode_desc': 'ڈیمو موڈ: نمونہ دستخطی اشیاء دکھا رہا ہے',
      'browse_menu_desc': 'مینو اشیاء براؤز کریں اور انہیں موجودہ آرڈر میں شامل کریں',
      'cancel_edit': 'ترمیم منسوخ کریں',
      'all_items': 'تمام اشیاء',
      'cart_details': 'کارٹ کی تفصیلات',
      'empty_cart': 'آپ کا کارٹ خالی ہے',
      'checkout': 'چیک آؤٹ',
      'total': 'کل',
      'subtotal': 'ذیلي ٹوٹل',
      'tax': 'ٹیکس',
      'discount': 'رعایت',
      'tip': 'ٹپ',
      'add_to_cart': 'کارٹ میں شامل کریں',
      'item_added': 'آئٹم کارٹ میں شامل ہو گیا',
      'order_type': 'آرڈر کی قسم',
      'dine_in': 'ڈائن ان',
      'takeaway': 'ٹیک اوے',
      'delivery': 'ڈیلیوری',
      'pickup': 'پک اپ',
      'select_table': 'ٹیبل منتخب کریں',
      'select_waiter': 'ویٹر منتخب کریں',
      'no_items_desc': 'ابھی تک کوئی آئٹم نہیں ہے۔ شامل کرنے کے لیے مینو کارڈ پر ٹیپ کریں۔',
      'item': 'آئٹم',
      'qty': 'تعداد',
      'price': 'قیمت',
      'split_bill': 'بل تقسیم کریں',
      'print': 'پرنٹ کریں',
      'send_to_kitchen': 'کچن کو بھیجیں',
      'add_tip': 'ٹپ شامل کریں',
      'apply_discount': 'رعایت لاگو کریں',
      'advance_paid': 'ایڈوانس ادا کیا گیا',
      'table': 'ٹیبل',
      'live_order_feed': 'لائیو آرڈر فیڈ',
      'search_orders': 'آرڈرز تلاش کریں',
      'all': 'تمام',
      'pending': 'زیر التواء',
      'completed': 'مکمل',
      'cancelled': 'منسوخ',
      'manager_dashboard': 'مینیجر ڈیش بورڈ',
      'operational_analytics': 'آپریشنل تجزیات',
      'orders_management': 'آرڈرز مینجمنٹ',
      'purchase_management': 'خریداری کا انتظام',
      'inventory_management': 'انوینٹری مینجمنٹ',
      'food_management': 'فوڈ مینجمنٹ',
      'categories': 'اقسام',
      'food_items': 'کھانے کی اشیاء',
      'production': 'پیداوار',
      'human_resource': 'انسانی وسائل',
      'customer_directory': 'صارفین کی ڈائریکٹری',
      'reports': 'رپورٹس',
      'reservations': 'تحفظات',
      'table_qr_codes': 'ٹیبل کیو آر کوڈز',
      'user_management': 'صارف کا انتظام',
      'role_permissions': 'کردار اور اجازتیں',
      'system_settings': 'سسٹم کی ترتیبات',
      'configuration': 'ترتیبات',
      'all_caps': 'سب',
      'appetizers': 'سٹارٹرز',
      'main_course': 'مین کورس',
      'desserts': 'میٹٹھا',
      'favorites': 'پسندیدہ',
      'recent': 'حالیہ',
      'no_orders_in': 'میں کوئی آرڈر نہیں ہے',
      'order_num_header': 'آرڈر نمبر #',
      'table_type_header': 'ٹیبل/قسم',
      'completed_header': 'مکمل',
      'start_time_header': 'شروع ہونے کا وقت',
      'items_header': 'اشیاء',
      'counter_duration_header': 'کاؤنٹر کا دورانیہ',
      'total_duration_header': 'کل دورانیہ',
      'status_header': 'حالت',
      'avg_prep_time': 'تیاری کا اوسط وقت',
      'avg_counter_time': 'کاؤنٹر کا اوسط وقت',
      'cancellation_rate': 'منسوخی کی شرح',
      'orders_in_view': 'منظر میں آرڈر',
      'order_velocity_analytics': 'آرڈر کی رفتار کے تجزیات',
      'lifecycle_tracking': 'آرڈر سے سروس تک لائف سائیکل ٹریکنگ',
      'live_bookings': 'لائیو بکنگ',
      'add_new_booking': 'نئی بکنگ شامل کریں',
      'guests': 'مہمان',
      'no_tables_found': 'کوئی ٹیبل نہیں ملی',
      'retry_fetch': 'دوبارہ کوشش کریں',
      'start_new_order': 'نیا آرڈر شروع کریں',
      'manage_active_order': 'فعال آرڈر کا انتظام کریں',
      'clear_table': 'ٹیبل خالی کریں',
      'manual_status_override': 'حالت کو دستی طور پر تبدیل کریں',
      'edit_table_details': 'ٹیبل کی تفصیلات ایڈٹ کریں',
      'delete_table': 'ٹیبل حذف کریں',
      'upcoming': 'آنے والا',
      'confirmed': 'تصدیق شدہ',
      'seated': 'بیٹھے ہوئے',
      'rejected': 'مسترد',
      'available': 'دستیاب',
      'occupied': 'مصروف',
      'reserved': 'بک شدہ',
      'needs_clearing': 'صفائی کی ضرورت ہے',
      'table_number': 'ٹیبل نمبر',
      'capacity': 'گنجائش',
      'table_updated': 'ٹیبل اپ ڈیٹ ہوگئی',
      'delete_table_confirm': 'کیا آپ واقعی ٹیبل ہٹانا چاہتے ہیں',
      'table_removed': 'ٹیبل کامیابی سے ہٹا دی گئی',
      'general': 'عام',
      'operations': 'آپریشنز',
      'branding': 'برانڈنگ',
      'payments': 'ادائیگی',
      'communications': 'رابطہ',
      'preparing': 'تیار ہو رہا ہے',
      'ready': 'تیار',
      'paid': 'ادا شدہ',
      'no_kds_orders': 'کچن میں کوئی فعال آرڈر نہیں ہے۔',
      'kitchen_production': 'کچن پروڈکشن',
      'active_tickets': 'فعال ٹکٹ',
      'notification_settings': 'اطلاعات کی ترتیبات',
      'new_order_received': 'نیا آرڈر موصول ہوا',
      'low_stock_alert': 'اسٹاک کم ہونے کی اطلاع',
      'payment_processed': 'ادائیگی مکمل ہوگئی',
      'kitchen_alert': 'کچن الرٹ',
      'system_update': 'سسٹم اپ ڈیٹ',
      'order_ready_pickup': 'آرڈر پک اپ کے لیے تیار ہے',
      'order_id': 'آرڈر نمبر #',
      'table_label': 'ٹیبل',
      'burger_patties_low': 'برگر پیٹیز کم ہو رہی ہیں',
      'pos_system_updated': 'پی او ایس سسٹم کامیابی سے اپ ڈیٹ ہو گیا',
      '2_min_ago': '2 منٹ پہلے',
      '15_min_ago': '15 منٹ پہلے',
      '1_hour_ago': '1 گھنٹہ پہلے',
      '2_hours_ago': '2 گھنٹے پہلے',
      '1_day_ago': '1 دن پہلے',
      'never': 'کبھی نہیں',
      '5_mins': '5 منٹ',
      '15_mins': '15 منٹ',
      '30_mins': '30 منٹ',
      '1_hour': '1 گھنٹہ',
      'dark_mode_desc': 'لائٹ اور ڈارک تھیم کے درمیان سوئچ کریں',
      'printer_desc': 'رسید پرنٹر ترتیب دیں',
      'sound_desc': 'اطلاعات کی آوازیں آن/آف کریں',
      'logout_desc': 'آٹو لاگ آؤٹ کا وقت مقرر کریں',
      'lang_desc': 'ایپ کی زبان تبدیل کریں',
      'conn_type': 'کنکشن کی قسم',
      'printer_ip': 'پرنٹر آئی پی ایڈریس',
      'send_test_print': 'ٹیسٹ پرنٹ بھیجیں',
      'order_notifications': 'آرڈر کی اطلاعات',
      'order_notifications_desc': 'نئے آرڈرز کے لیے آواز چلائیں',
      'notification_volume': 'اطلاعات کی آواز',
      'select_sound': 'آواز منتخب کریں',
      'test_sound': 'آواز چیک کریں',
      'lang_settings': 'زبان کی ترتیبات',
      'auto_sync_active': 'خودکار مطابقت فعال ہے (15s)',
      'live_data_sync': 'آن لائن آرڈرز اور ریزرویشن کے ساتھ لائیو ڈیٹا مطابقت',
      'todays_sale': 'آج کی فروخت',
      'todays_orders': 'آج کے آرڈرز',
      'lifetime_orders': 'کل آرڈرز',
      'total_customers': 'کل صارفین',
      'order_service_split': 'سروس کی تقسیم',
      'pick_up': 'پک اپ',
      'payment_method_coverage': 'ادائیگی کا طریقہ',
      'cash': 'نقد',
      'card_terminal': 'کارڈ/ٹرمینل',
      'online_order': 'آن لائن آرڈر',
      'daily_deductions': 'یومیہ کٹوتیاں/اضافے',
      'tips_today': 'ٹپ (آج)',
      'discounts_label': 'رعایت',
      'pending_orders_kds': 'زیر التواء آرڈرز (KDS)',
      'awaiting_payment': 'ادائیگی کا انتظار',
      'today_reservations': 'آج کی ریزرویشن',
      'active_orders': 'فعال آرڈرز',
      'monthly_revenue_trend': 'ماہانہ آمدنی - 6 ماہ کا رجحان',
      'customize_item': 'اپنی مرضی سے بنائیں',
      'variant': 'ویریئنٹ',
      'extras_label': 'اضافی',
      'official_receipt': 'سرکاری رسید',
      'thank_you_visiting': 'آپ کا شکریہ!',
      'print_now': 'ابھی پرنٹ کریں',
      'split_bill_dialog': 'بل تقسیم کریں',
      'split_by': 'تقسیم کریں',
      'people': 'افراد',
      'total_bill': 'کل بل',
      'each_person': 'فی شخص',
      'confirm_split': 'تقسیم کی تصدیق کریں',
      'search_table': 'ٹیبل نمبر تلاش کریں...',
      'clear_takeaway': 'کلیئر / ٹیک اوے',
      'table_number_hint': 'ٹیبل نمبر (جیسے T15)',
      'capacity_seats': 'گنجائش (نشستیں)',
      'add_table': 'ٹیبل شامل کریں',
      'table_type': 'ٹیبل کی قسم',
      'table_size': 'ٹیبل کا سائز',
      'chairs_count': 'کرسیاں #',
      'search_items': 'آئٹم تلاش کریں...',
      'sent_to_printer': 'پرنٹر کو بھیج دیا گیا...',
      'settings_not_loaded': 'ترتیبات لوڈ نہیں ہوئیں',
      'retry': 'دوبارہ کوشش کریں',
      'enabled': 'فعال',
      'disabled': 'غیر فعال',
      'environment': 'ماحول:',
      'test_connection': 'کنکشن جانچیں',
      'send_test_message': 'ٹیسٹ پیغام بھیجیں',
      'send_test_email_btn': 'ٹیسٹ ای میل بھیجیں',
      'save': 'محفوظ کریں',
      'custom_item': 'کسٹم آئٹم',
      'capacity_label': 'گنجائش',
      'general_settings': 'عمومی ترتیبات',
      'general_settings_desc': 'ریستورین کی بنیادی شناخت اور ترجیحات ترتیب کریں.',
      'restaurant_info': 'ریستورین کی معلومات',
      'legal_name': 'قانونی نام',
      'legal_name_desc': 'رسیدوں اور قانونی دستاویزات پر دکھائی جاتی ہے',
      'primary_currency': 'بنیادی کرنسی',
      'primary_currency_desc': 'تمام مالی لین دین اس کا استعمال کریں گے',
      'interface_theme': 'انٹرفیس تھیم',
      'interface_theme_desc': 'تمام ٹرمینل انٹرفیسز کا بصری انداز',
      'operational_controls': 'آپریشنل کنٹرولز',
      'operational_controls_desc': 'ٹیکسز، فیس اور خودکار سسٹم کا انتظام کریں.',
      'taxes_gratuity': 'ٹیکس اور ٹپ',
      'kitchen_bookings': 'کچن اور بکنگز',
      'order_channels': 'آرڈر چینلز',
      'branding_desc': 'POS اور ویب پر اپنی بصری شناخت کا انتظام کریں.',
      'visual_assets': 'بصری اساسیں',
      'communications_desc': 'واٹس اپ، SMS اور ای میل ترتیب کریں.',
      'enable_vat': 'VAT/ٹیکس فعال کریں',
      'enable_vat_desc': 'آرڈر کے مجموعی پر خودکار ٹیکس کا اطلاق کریں',
      'tax_rate_label': 'ٹیکس کی شرح (%)',
      'tax_rate_desc': 'سیلز ٹیکس کے لیے معیاری فیصد',
      'default_gratuity': 'ڈیفالٹ ٹپ %',
      'default_gratuity_desc': 'بڑے گروپس کے لیے خودکار سروس چارج',
      'kds_timer': 'KDS وارننگ ٹائمر',
      'kds_timer_desc': 'آرڈر کے تاخیر سے نشان زد ہونے سے پہلے کے منٹ',
      'enable_booking_fee': 'بکنگ فیس فعال کریں',
      'enable_booking_fee_desc': 'پیشگی ریزرویشن کے لیے صارفین سے چارج کریں',
      'booking_fee_amount': 'بکنگ فیس کی رقم',
      'booking_fee_amount_desc': 'فی ریزرویشن مقررہ فیس',
      'qr_table_ordering': 'QR ٹیبل آرڈرنگ',
      'qr_table_ordering_desc': 'صارفین کو QR کوڈز کے ذریعے آرڈر کرنے کی اجازت دیں',
      'home_delivery': 'ہوم ڈیلیوری',
      'home_delivery_desc': 'ویب سائٹ پر ڈیلیوری کا آپشن فعال کریں',
      'customer_pickup': 'کسٹمر پک اپ',
      'customer_pickup_desc': 'ویب سائٹ پر پک اپ کا آپشن فعال کریں',
      'out_of_stock': 'اسٹاک میں نہیں ہے',
      'clear_btn': 'صاف کریں',
      'update_order': 'آرڈر اپ ڈیٹ کریں',
      'pay_now': 'ابھی ادا کریں',
      'order_updated_success': 'آرڈر کامیابی سے اپ ڈیٹ ہو گیا!',
      'order_placed_success': 'آرڈر کامیابی سے دے دیا گیا! کچن کو بھیج دیا گیا۔',
      'server_error_retry': 'سرور کی خرابی۔ دوبارہ کوشش کریں۔',
      'connection_error_msg': 'کنکشن کی خرابی',
      'table_added_floor': 'ٹیبل فلور پلان میں شامل کر دی گئی ہے',
      'select_slot': 'وقت منتخب کریں',
      'choose_table': 'ٹیبل منتخب کریں',
      'review_confirm': 'جائزہ لیں اور تصدیق کریں',
      'visit_time_prompt': 'آپ کب آنا چاہیں گے؟',
      'select_available_table': 'دستیاب ٹیبل منتخب کریں',
      'guest_prompt': 'مہمان کے بارے میں بتائیں',
      'full_name': 'پورا نام',
      'whatsapp_phone': 'واٹس اپ / فون',
      'email_address': 'ای میل ایڈریس',
      'special_requests': 'خصوصی درخواستیں / نوٹس',
      'reservation_summary': 'ریزرویشن کا خلاصہ',
      'card_details': 'کارڈ کی تفصیلات',
      'powered_by_stripe': 'Stripe کے ذریعے',
      'card_number': 'کارڈ نمبر',
      'expiry_date': 'خاتمے کی تاریخ',
      'cvc': 'CVC',
      'back_btn': 'پیچھے',
      'next_btn': 'اگلا',
      'confirm_reservation': 'ریزرویشن کی تصدیق کریں',
      'please_select_table': 'براہ کرم ٹیبل منتخب کریں',
      'name_phone_required': 'نام اور فون نمبر ضروری ہیں',
      'reservation_success': 'ریزرویشن کامیابی سے بن گئی ہے!',
      'reservation_failed': 'ریزرویشن بنانے میں ناکامی',
      'reject_order': 'آرڈر مسترد کریں',
      'rejection_reason_hint': 'مثال کے طور پر: اسٹاک ختم، کچن بہت مصروف ہے...',
      'confirm_rejection': 'مسترد کرنے کی تصدیق کریں',
      'reason_required': 'وجہ ضروری ہے',
      'step_label': 'مرحلہ',
      'of_label': 'میں سے',
      'no_tables_available': 'کوئی ٹیبل دستیاب نہیں ہے',
      'try_different_date': 'کوئی اور تاریخ یا وقت منتخب کرنے کی کوشش کریں۔',
      'pers_label': 'افراد',
      'date_label': 'تاریخ',
      'time_label': 'وقت',
      'guests_label': 'مہمانوں',
      'people_label': 'افراد',
      'seats_label': 'نشستیں',
      'advance_booking_fee': 'ایڈوانس بکنگ فیس',
      'collect_at_counter': 'کاؤنٹر پر مہمان سے وصول کریں',
      'card': 'کارڈ',
      'fee_policy_desc': 'فیس فائنل بل سے منہا کی جائے گی لیکن نہ آنے کی صورت میں ناقابل واپسی ہوگی۔',
      'free_status': 'خالی',
      'occupied_status': 'مصروف',
      'pax_label': 'افراد',
      'link_copied_for': 'لنک کاپی کر لیا گیا برائے',
      'copy_link': 'لنک کاپی کریں',
      'settings_updated_msg': 'ترتیبات کامیابی سے اپ ڈیٹ ہو گئیں!',
      'failed_to_save': 'ترتیبات محفوظ کرنے میں ناکامی',
      'messaging_integration': 'میسجنگ انٹیگریشن',
      'twilio_setup_desc': 'واٹس اپ اور SMS اطلاعات کے لیے Twilio ترتیب دیں۔',
      'account_sid': 'اکاؤنٹ SID',
      'auth_token': 'آتھ ٹوکن',
      'sender_number': 'بھیجنے والے کا نمبر',
      'waba_id': 'WABA ID',
      'test_msg_desc': 'ٹیسٹ پیغام بھیجنے کے لیے فون نمبر درج کریں۔',
      'test_phone_number': 'ٹیسٹ فون نمبر',
      'sending_test_msg': 'ٹیسٹ پیغام بھیج رہا ہے برائے',
      'test_msg_success': 'کامیاب! ٹیسٹ پیغام بھیج دیا گیا۔',
      'error_label': 'غلطی',
      'email_notifications': 'ای میل اور اطلاعات',
      'smtp_setup_desc': 'خودکار ای میلز بھیجنے کے لیے اپنا SMTP سرور ترتیب دیں۔',
      'smtp_host': 'SMTP ہوسٹ',
      'smtp_port': 'SMTP پورٹ',
      'username': 'صارف کا نام',
      'password': 'پاس ورڈ',
      'from_email': 'ای میل سے',
      'from_name': 'بھیجنے والے کا نام',
      'test_email_desc': 'ٹیسٹ ای میل بھیجنے کے لیے ای میل ایڈریس درج کریں۔',
      'test_email_address': 'ٹیسٹ ای میل ایڈریس',
      'sending_test_email': 'ٹیسٹ ای میل بھیج رہا ہے برائے',
      'test_email_success': 'کامیاب! ٹیسٹ ای میل بھیج دی گئی۔',
      'order_marked_status': 'آرڈر کو نشان زد کیا گیا بطور',
      'failed_update_status': 'حالت اپ ڈیٹ کرنے میں ناکامی',
      'item_removed_order': 'آئٹم آرڈر سے ہٹا دیا گیا۔',
      'category_created_success': 'کیٹیگری کامیابی سے بن گئی ہے',
      'category_failed_create': 'کیٹیگری بنانے میں ناکامی',
      'category_updated_success': 'کیٹیگری کامیابی سے اپ ڈیٹ ہو گئی',
      'category_deleted_success': 'کیٹیگری کامیابی سے حذف ہو گئی',
      'menu_item_created_success': 'مینو آئٹم کامیابی سے بن گیا ہے',
      'menu_item_updated_success': 'مینو آئٹم کامیابی سے اپ ڈیٹ ہو گیا',
      'menu_item_deleted_success': 'مینو آئٹم کامیابی سے حذف ہو گیا',
      'setting_updated_success': 'ترتیب کامیابی سے اپ ڈیٹ ہو گئی',
      'user_created_success': 'صارف کامیابی سے بن گیا ہے',
      'user_updated_success': 'صارف کامیابی سے اپ ڈیٹ ہو گیا',
      'user_deleted_success': 'صارف کامیابی سے حذف ہو گیا',
      'permissions_updated': 'اجازتیں اپ ڈیٹ ہو گئیں',
      'date_btn': 'تاریخ',
      'time_btn': 'وقت',
      'guests_btn': 'مہمانوں',
      'coming_soon': 'جلد آ رہا ہے',
      'back_to_dashboard': 'ڈیش بورڈ پر واپس جائیں',
      'error_details': 'غلطی کی تفصیلات',
      'show_details': 'تفصیلات دیکھیں',
      'staff_management': 'اسٹاف مینجمنٹ',
      'staff_mgmt_desc': 'اپنی ریستورین ٹیم اور رسائی کے لیولز کا انتظام کریں',
      'add_new_staff': 'نیا اسٹاف شامل کریں',
      'no_users_found': 'کوئی صارف نہیں ملا۔',
      'roles_permissions_title': 'کردار اور اجازتیں',
      'roles_desc': 'ہر ملازمت کے کردار کے لیے رسائی کے لیولز ترتیب دیں',
      'edit_permissions_btn': 'اجازتیں ترمیم کریں',
      'assign_role': 'کردار تفویض کریں',
      'delete_staff_q': 'اسٹاف حذف کریں؟',
      'remove_user_confirm': 'کیا آپ واقعی صارف کو سسٹم سے ہٹانا چاہتے ہیں؟',
      'business_intelligence': 'بزنس انٹیلی جنس',
      'no_data': 'کوئی ڈیٹا نہیں ہے',
      'error_loading_page': 'اوہ! اس صفحہ کو لوڈ کرنے میں کچھ غلط ہو گیا ہے۔',
      'close_btn': 'بند کریں',
      'edit_staff_details': 'اسٹاف کی تفصیلات ترمیم کریں',
      'first_name': 'پہلا نام',
      'last_name': 'آخری نام',
      'email_label': 'ای میل',
      'phone_label': 'فون',
      'cancel_btn': 'منسوخ کریں',
      'create_btn': 'بنائیں',
      'save_btn': 'محفوظ کریں',
      'delete_btn': 'حذف کریں',
      'summary_tab': 'خلاصہ',
      'sales_log_tab': 'سیلز لاگ',
      'product_mix_tab': 'پروڈکٹ مکس',
      'staff_tab': 'اسٹاف',
      'net_sales': 'کل فروخت',
      'total_orders': 'کل آرڈرز',
      'avg_order': 'اوسط آرڈر',
      'est_profit': 'تخمینہ منافع',
      'operational_status': 'آپریشنل حالت',
      'top_selling_items': 'سب سے زیادہ فروخت ہونے والی اشیاء (30 دن)',
      'recent_transactions': 'حالیہ لین دین',
      'id_col': 'آئی ڈی',
      'time_col': 'وقت',
      'type_col': 'قسم',
      'total_col': 'کل',
      'status_col': 'حالت',
      'no_sales_data': 'سیلز کا کوئی ڈیٹا نہیں ہے',
      'no_shift_data': 'آج کے لیے شفٹ کا کوئی ڈیٹا دستیاب نہیں ہے',
      'shift_label': 'شفٹ',
      'back_to_analytics': 'اینالیٹکس پر واپس جائیں',
      'clock_in_out': 'کلاک ان/آؤٹ',
      'recent_activity': 'حالیہ سرگرمی',
      'staff_online': 'اسٹاف آن لائن',
      'quick_clock_in_test': 'ٹیسٹنگ کے لیے کوئیک کلاک ان',
      'clock_in_test': 'کلاک ان (جان اسٹاف)',
      'messages_inquiries': 'پیغامات اور پوچھ گچھ',
      'no_messages_yet': 'ابھی تک کوئی پیغام نہیں ہے',
      'mark_as_read': 'پڑھا ہوا نشان زد کریں',
      'print_all_qr': 'تمام QR کوڈز پرنٹ کریں',
      'version_label': 'ورژن',
      'primary_logo_upload': 'پرائمری لوگو اپ لوڈ',
      'main_brand_logo_desc': 'ہیڈر میں دکھایا جانے والا مین برانڈ لوگو',
      'secondary_logo_upload': 'سیکنڈری لوگو اپ لوڈ',
      'secondary_branding_desc': 'سیکنڈری برانڈنگ (مثلاً حلال لوگو)',
      'environment_label': 'انوائرمنٹ',
      'waiting_status': 'انتظار کر رہا ہے',
      'edit_permissions_title': 'اجازتیں ترمیم کریں',
      'received_at': 'موصول ہوا وقت',
      'from_label': 'سے',
      'system_reset': 'سسٹم ری سیٹ',
      'system_maintenance': 'سسٹم مینٹیننس',
      'reset_transactional_data_desc': 'ٹرانزیکشنل ریکارڈز کو ختم کرکے انتظامی دیکھ بھال کریں جبکہ ساختی ڈیٹا کو برقرار رکھیں۔',
      'danger_zone': 'خطرہ زون',
      'reset_warning_text': 'یہ عمل تمام آرڈرز، ادائیگیوں اور آپریشنل ہسٹری کو مستقل طور پر حذف کر دے گا۔ اسے واپس نہیں کیا جا سکتا۔',
      'data_impact_analysis': 'ڈیٹا اثر تجزیہ',
      'orders_payments_reservations': 'آرڈرز، ادائیگیاں اور ریزرویشنز',
      'expenses_purchases': 'اخراجات اور خریداری کے آرڈرز',
      'menu_items_categories': 'مینو آئٹمز اور زمرے',
      'users_roles_permissions': 'صارفین، کردار اور اجازتیں',
      'table_layouts_settings': 'ٹیبل لے آؤٹ اور ترتیبات',
      'reset_transactional_data': 'ٹرانزیکشنل ڈیٹا ری سیٹ کریں',
      'will_be_deleted': 'حذف کر دیا جائے گا',
      'will_be_preserved': 'برقرار رکھا جائے گا',
      'are_you_sure': 'کیا آپ کو یقین ہے؟',
      'reset_confirmation_detailed': 'آپ سسٹم سے تمام ٹرانزیکشنل ڈیٹا کو صاف کرنے والے ہیں۔ اس سے آپ کے ڈیش بورڈ میٹرکس اور آرڈر ہسٹری صفر ہو جائے گی۔ ماسٹر ڈیٹا جیسے آپ کا مینو اور عملہ اچھوتا رہے گا۔',
      'confirm_reset': 'ری سیٹ کی تصدیق کریں',
      'transactional_reset_success': 'ٹرانزیکشنل ڈیٹا کامیابی کے ساتھ ری سیٹ ہو گیا ہے۔',
      'payment_success_message': 'ادائیگی کامیابی کے ساتھ مکمل ہو گئی ہے!',
      'order_payment': 'آرڈر کی ادائیگی',
      'unpaid': 'غیر ادا شدہ',
      'amount_due': 'واجب الادا رقم',
      'confirm_payment': 'ادائیگی کی تصدیق کریں',
      'complete_payment': 'ادائیگی مکمل کریں',
    }
  };

  void setLanguage(String language) {
    // Case-insensitive lookup
    final matchedKey = _translations.keys.firstWhere(
      (k) => k.toLowerCase() == language.toLowerCase(),
      orElse: () => '',
    );
    
    if (matchedKey.isNotEmpty) {
      _currentLanguage = matchedKey;
      notifyListeners();
    }
  }

  String translate(String key) {
    final translation = _translations[_currentLanguage]?[key];
    if (translation != null) return translation;
    
    // Fallback: Return key with underscores replaced by spaces and Title Cased
    return key.split('_').map((word) {
      if (word.isEmpty) return word;
      return word[0].toUpperCase() + word.substring(1).toLowerCase();
    }).join(' ');
  }
}
