import 'package:flutter/material.dart';

class LocalizationService extends ChangeNotifier {
  String _currentLanguage = 'English';

  String get currentLanguage => _currentLanguage;

  final Map<String, Map<String, String>> _translations = {
    'English': {
      '15_min_ago': '15 min ago',
      '15_mins': '15 Minutes',
      '1_day_ago': '1 day ago',
      '1_hour': '1 Hour',
      '1_hour_ago': '1 hour ago',
      '2_hours_ago': '2 hours ago',
      '2_min_ago': '2 min ago',
      '30_mins': '30 Minutes',
      '5_mins': '5 Minutes',
      'account_sid': 'Account SID',
      'active_orders': 'Active Orders',
      'active_permissions': 'Active Permissions',
      'active_tickets': 'active tickets',
      'add_items_to_cart_warning': '',
      'add_new_booking': 'Add New Booking',
      'add_new_item': 'Add New Item',
      'add_new_staff': 'ADD NEW STAFF',
      'add_new_table': 'Add New Table',
      'add_table': 'ADD TABLE',
      'add_tip': 'Add Tip',
      'add_to_cart': 'Add to Cart',
      'advance_booking_fee': 'Advance Booking Fee',
      'advance_paid': 'Advance Paid',
      'all': 'All',
      'all_caps': 'ALL',
      'all_items': 'All Items',
      'amount_due': 'Amount Due',
      'appetizers': 'APPETIZERS',
      'apply_discount': 'Apply Discount',
      'are_you_sure': 'Are you absolutely sure?',
      'assign_role': 'Assign Role',
      'assign_table': 'Assign Table',
      'attention': 'Attention',
      'aura_purple': 'Aura Purple',
      'auth_token': 'Auth Token',
      'auto_logout': 'Auto Logout',
      'auto_sync_active': 'Auto-sync Active (15s)',
      'available': 'Available',
      'avg_counter_time': 'Avg. Counter Time',
      'avg_order': 'AVG. ORDER',
      'avg_prep_time': 'Avg. Prep Time',
      'awaiting_payment': 'Awaiting Payment',
      'back_btn': 'BACK',
      'back_to_analytics': 'BACK TO ANALYTICS',
      'back_to_dashboard': 'BACK TO DASHBOARD',
      'bluetooth': 'Bluetooth',
      'booking_fee': 'Booking Fee Amount',
      'booking_fee_amount': 'Booking Fee Amount',
      'booking_fee_amount_desc': 'Fixed fee per reservation',
      'branding': 'Branding',
      'branding_desc': 'Manage your visual identity across POS and Web.',
      'browse_menu_desc': 'Browse menu items and add them to the current order',
      'burger_patties_low': 'Burger patties running low',
      'business_intelligence': 'Business Intelligence',
      'cancel': 'Cancel',
      'cancel_btn': 'CANCEL',
      'cancel_edit': 'CANCEL EDIT',
      'cancellation_rate': 'Cancellation Rate',
      'cancelled': 'Cancelled',
      'capacity': 'Capacity',
      'capacity_label': 'Capacity',
      'capacity_seats': 'Capacity (Seats)',
      'card': 'Card',
      'card_details': 'Card Details',
      'card_number': 'Card Number',
      'card_terminal': 'Card/Terminal',
      'cart_details': 'Cart Details',
      'cash': 'Cash',
      'categories': 'Categories',
      'category_created_success': 'Category created successfully',
      'category_deleted_success': 'Category deleted successfully',
      'category_failed_create': 'Failed to create category',
      'category_updated_success': 'Category updated successfully',
      'chairs_count': 'Chairs #',
      'checkout': 'Checkout',
      'checkout_btn': 'CHECKOUT',
      'choose_table': 'Choose Table',
      'clear_btn': 'CLEAR',
      'clear_filters': 'Clear Filters',
      'clear_table': 'Clear Table',
      'clear_takeaway': 'Clear / Takeaway',
      'clock_in_out': 'Clock In/Out',
      'clock_in_test': 'Clock In (John Staff)',
      'close': 'Close',
      'close_btn': 'Close',
      'collect_at_counter': 'Collect from guest at counter',
      'coming_soon': 'Coming Soon',
      'communications': 'Communications',
      'communications_desc': 'Configure WhatsApp, SMS, and Email automation.',
      'complete_payment': 'COMPLETE PAYMENT',
      'completed': 'Completed',
      'completed_header': 'COMPLETED',
      'configuration': 'Configuration',
      'confirm_payment': 'CONFIRM PAYMENT',
      'confirm_rejection': 'CONFIRM REJECTION',
      'confirm_reservation': 'CONFIRM RESERVATION',
      'confirm_reset': 'CONFIRM RESET',
      'confirm_split': 'Confirm Split',
      'confirmed': 'Confirmed',
      'conn_type': 'Connection Type',
      'connection_error_msg': 'Connection Error',
      'copy_link': 'Copy Link',
      'counter_duration_header': 'COUNTER DURATION',
      'create_btn': 'CREATE',
      'current_stock': 'Current Stock',
      'custom_item': 'Custom Item',
      'customer_added_success': 'Customer added successfully',
      'customer_deleted_success': 'Customer deleted successfully',
      'customer_directory': 'Customer Directory',
      'customer_pickup': 'Customer Pickup',
      'customer_pickup_desc': 'Enable pickup option on website',
      'customer_updated_success': 'Customer updated successfully',
      'customize_item': 'Customize',
      'cvc': 'CVC',
      'daily_deductions': 'Daily Deductions/Extras',
      'danger_zone': 'Danger Zone',
      'dark_mode': 'Dark Mode',
      'dark_mode_desc': 'Toggle between light and dark theme',
      'dashboard': 'Dashboard',
      'data_impact_analysis': 'Data Impact Analysis',
      'date_btn': 'DATE',
      'date_label': 'Date',
      'date_range': 'Date Range',
      'default_gratuity': 'Default Gratuity %',
      'default_gratuity_desc': 'Automatic service charge for large groups',
      'delete_btn': 'DELETE',
      'delete_staff_q': 'Delete Staff?',
      'delete_success': 'Deleted successfully',
      'delete_table': 'Delete Table',
      'delete_table_confirm': 'Are you sure you want to remove Table',
      'delivery': 'Delivery',
      'demo_mode_desc': 'DEMO MODE: Showing sample signature items',
      'desserts': 'DESSERTS',
      'detailed_orders_report': 'Detailed Orders Report',
      'dine_in': 'Dine-In',
      'disabled': 'Disabled',
      'discount': 'Discount',
      'discounts_label': 'Discounts',
      'each_person': 'Each Person',
      'edit': 'Edit',
      'edit_item': 'Edit Item',
      'edit_permissions_btn': 'EDIT PERMISSIONS',
      'edit_permissions_title': 'Edit Permissions',
      'edit_staff_details': 'Edit Staff Details',
      'edit_table_details': 'Edit Table Details',
      'email_address': 'Email Address',
      'email_label': 'Email',
      'email_notifications': 'Email & Notifications',
      'emerald_green': 'Emerald Green',
      'empty_cart': 'Your cart is empty',
      'enable_booking_fee': 'Enable Booking Fee',
      'enable_booking_fee_desc': 'Charge customers for advance reservations',
      'enable_vat': 'Enable VAT/Tax',
      'enable_vat_desc': 'Apply automatic tax calculation to order totals',
      'enabled': 'Enabled',
      'enter_capacity_warning': 'Please specify table capacity.',
      'enter_guest_name_warning': 'Please enter the guest name.',
      'enter_guest_phone_warning': 'Please enter the guest phone number.',
      'enter_table_number_warning': 'Please enter a table number.',
      'environment': 'Environment:',
      'environment_label': 'Environment',
      'error_adding_customer': 'Error adding customer',
      'error_deleting_customer': 'Error deleting customer',
      'error_details': 'Error Details',
      'error_label': 'Error',
      'error_loading_page': 'Oops! Something went wrong loading this page.',
      'error_updating_customer': 'Error updating customer',
      'est_profit': 'EST. PROFIT',
      'expenses_purchases': 'Expenses & Purchase Orders',
      'expiry_date': 'Expiry Date',
      'export_pdf': 'Export PDF',
      'extras_label': 'Extras',
      'failed_to_delete': 'Failed to delete',
      'failed_to_load_inventory': 'Failed to load inventory',
      'failed_to_save': 'Failed to save',
      'failed_update_status': 'Failed to update status',
      'favorites': 'FAVORITES',
      'fee_policy_desc': '',
      'fill_guest_details_warning': '',
      'filter_by_status': 'Filter by Status',
      'filter_by_type': 'Filter by Type',
      'first_name': 'First Name',
      'food_items': 'Food Items',
      'food_management': 'Food Management',
      'free_status': 'Free',
      'from_email': 'From Email',
      'from_label': 'From',
      'from_name': 'From Name',
      'full_name': 'Full Name',
      'general': 'General',
      'general_settings': 'General Settings',
      'general_settings_desc': '',
      'guest_prompt': 'Tell us about the guest',
      'guests': 'Guests',
      'guests_btn': 'GUESTS',
      'guests_label': 'Guests',
      'home_delivery': 'Home Delivery',
      'home_delivery_desc': 'Enable delivery option on website',
      'human_resource': 'Human Resource',
      'id_col': 'ID',
      'interactive_floor_plan': 'Interactive Floor Plan',
      'interface_theme': 'Interface Theme',
      'interface_theme_desc': 'Visual style for all terminal interfaces',
      'invalid_ip_format': 'Invalid IP Address format',
      'inventory_management': 'Inventory Management',
      'item': 'Item',
      'item_added': 'Item added to cart',
      'item_name': 'Item Name',
      'item_removed_order': 'Item removed from order.',
      'items_header': 'ITEMS',
      'kds': 'KDS',
      'kds_timer': 'KDS Warning Timer',
      'kds_timer_desc': 'Minutes before order highlights as delayed',
      'kitchen_alert': 'Kitchen Alert',
      'kitchen_bookings': 'Kitchen & Bookings',
      'kitchen_production': 'Kitchen Production',
      'lang_desc': 'Change app language',
      'lang_settings': 'Language Settings',
      'language': 'Language',
      'last_name': 'Last Name',
      'legal_name': 'Legal Name',
      'legal_name_desc': 'Displayed on receipts and legal docs',
      'lifecycle_tracking': 'Lifecycle tracking from Order to Service',
      'lifetime_orders': 'Lifetime Orders',
      'link_copied_for': 'Link copied for',
      'live_bookings': 'Live Bookings',
      'live_data_sync': '',
      'live_order_feed': 'Live Order Feed',
      'logout_desc': 'Set automatic logout time',
      'logout_not_connected': 'Logout functionality not connected',
      'low_stock_alert': 'Low Stock Alert',
      'main_brand_logo_desc': 'Main brand logo shown in the header',
      'main_course': 'MAIN COURSE',
      'main_course_items': 'Main Course Items',
      'manage_active_order': 'Manage Active Order',
      'manager_dashboard': 'MANAGER DASHBOARD',
      'manual_status_override': 'Manual Status Override',
      'mark_all_read': 'Mark All Read',
      'mark_as_read': 'Mark as Read',
      'menu_item_created_success': 'Menu item created successfully',
      'menu_item_deleted_success': 'Menu item deleted successfully',
      'menu_item_updated_success': 'Menu item updated successfully',
      'menu_items_categories': 'Menu Items & Categories',
      'messages_inquiries': 'Messages & Inquiries',
      'messaging_integration': 'Messaging Integration',
      'midnight_blue': 'Midnight Blue',
      'min': 'Min',
      'min_stock_level': 'Min Stock Level',
      'mission_control': 'Mission Control Center',
      'monthly_revenue_trend': 'Monthly Revenue - 6 Month Trend',
      'name_phone_required': 'Name and Phone are required',
      'needs_clearing': 'Needs Clearing',
      'net_sales': 'NET SALES',
      'network': 'Network',
      'never': 'Never',
      'new_order_received': 'New Order Received',
      'next_btn': 'NEXT',
      'no_data': 'No data',
      'no_items_desc': 'No items yet. Tap a menu card to add.',
      'no_kds_orders': 'No active orders in the kitchen',
      'no_messages_yet': 'No messages yet',
      'no_orders_in': 'No orders in',
      'no_reservations_found': 'No reservations found',
      'no_results_found': 'No results found',
      'no_sales_data': 'No sales data',
      'no_shift_data': 'No shift data available for today',
      'no_tables_available': 'No tables available',
      'no_tables_found': 'No tables found',
      'no_users_found': 'No users found.',
      'notification_settings': 'Notification Settings',
      'notification_volume': 'Notification Volume',
      'notifications': 'Notifications',
      'occupied': 'Occupied',
      'occupied_status': 'Occupied',
      'of_label': 'of',
      'official_receipt': 'Official Receipt',
      'ok': 'OK',
      'online_order': 'Online Order',
      'operational_analytics': 'Operational Analytics',
      'operational_controls': 'Operational Controls',
      'operational_controls_desc': '',
      'operational_status': 'Operational Status',
      'operations': 'Operations',
      'order_channels': 'Order Channels',
      'order_id': 'Order #',
      'order_marked_status': 'Order marked as',
      'order_notifications': 'Order Notifications',
      'order_notifications_desc': 'Play sound for new orders',
      'order_num_header': 'ORDER #',
      'order_payment': 'Order Payment',
      'order_placed_success': 'Order placed successfully! Sent to KDS.',
      'order_ready_pickup': 'Order ready for pickup',
      'order_service_split': 'Order Service Split',
      'order_type': 'Order Type',
      'order_updated_success': 'Order updated successfully!',
      'order_velocity_analytics': 'Order Velocity Analytics',
      'orders': 'Orders',
      'orders_in_view': 'Orders in View',
      'orders_management': 'Orders Management',
      'orders_payments_reservations': 'Orders, Payments & Reservations',
      'out_of_stock': 'OUT OF STOCK',
      'paid': 'Paid',
      'password': 'Password',
      'pax_label': 'pax',
      'pay_all': 'Pay All',
      'pay_first': 'Pay First',
      'pay_last': 'Pay Last',
      'pay_now': 'PAY NOW',
      'payment_method_coverage': 'Payment Method Coverage',
      'payment_policy': 'Payment Policy',
      'payment_policy_desc': '',
      'payment_processed': 'Payment Processed',
      'payment_success_message': 'Payment processed successfully!',
      'payments': 'Payments',
      'pending': 'Pending',
      'pending_orders_kds': 'Pending Orders (KDS)',
      'people': 'people',
      'people_label': 'People',
      'permissions_updated': 'Permissions updated',
      'pers_label': 'Pers.',
      'phone_label': 'Phone',
      'pick_up': 'Pick-up',
      'pickup': 'Pickup',
      'please_select_table': 'Please select a table',
      'popular_customizations': 'Popular Customizations',
      'pos': 'POS',
      'pos_system_updated': 'POS system updated successfully',
      'powered_by_stripe': 'Powered by Stripe',
      'preparing': 'Preparing',
      'price': 'Price',
      'primary_currency': 'Primary Currency',
      'primary_currency_desc': 'All financial transactions will use this',
      'primary_logo_upload': 'Primary Logo Upload',
      'print': 'PRINT',
      'print_all_qr': 'Print All QR Codes',
      'print_now': 'PRINT NOW',
      'printer_desc': 'Configure receipt printer',
      'printer_ip': 'Printer IP Address',
      'printer_settings': 'Printer Settings',
      'product_mix_tab': 'PRODUCT MIX',
      'production': 'Production',
      'provide_rejection_reason': 'Please provide a reason for rejecting order',
      'purchase_inventory_hub': 'Purchase & Inventory Hub',
      'purchase_management': 'Purchase Management',
      'qr_menu_order': 'QR Menu Order',
      'qr_table_ordering': 'QR Table Ordering',
      'qr_table_ordering_desc': 'Allow customers to order via QR codes',
      'qty': 'Qty',
      'quick_clock_in_test': 'Quick Clock-In for testing',
      'ready': 'Ready',
      'reason_required': 'Reason is required',
      'received_at': 'Received at',
      'recent': 'RECENT',
      'recent_activity': 'Recent Activity',
      'recent_transactions': 'Recent Transactions',
      'reject_order': 'Reject Order',
      'rejected': 'Rejected',
      'rejection_reason_hint': 'e.g., Out of stock, Kitchen too busy...',
      'remove_user_confirm': '',
      'reports': 'Reports',
      'reservation': 'Reservation',
      'reservation_failed': 'Failed to create reservation',
      'reservation_success': 'Reservation created successfully!',
      'reservation_summary': 'Reservation Summary',
      'reservations': 'Reservations',
      'reserved': 'Reserved',
      'reset_confirmation_detailed': '',
      'reset_transactional_data': 'Reset Transactional Data',
      'reset_transactional_data_desc': '',
      'reset_warning_text': '',
      'restaurant_info': 'Restaurant Information',
      'retry': 'RETRY',
      'retry_fetch': 'RETRY FETCH',
      'review_confirm': 'Review & Confirm',
      'role_admin': 'Role: Administrator',
      'role_permissions': 'Role & Permissions',
      'roles_desc': 'Configure access levels for each job role',
      'roles_permissions_title': 'Roles & Permissions',
      'sales_log_tab': 'SALES LOG',
      'save': 'Save',
      'save_btn': 'SAVE',
      'save_changes': 'Save Changes',
      'save_item': 'Save Item',
      'save_settings': 'Save Settings',
      'save_success': 'Saved successfully',
      'search_items': 'Search items...',
      'search_orders': 'Search Orders',
      'search_table': 'Search table number...',
      'seat_guest': 'Seat Guest',
      'seated': 'Seated',
      'seats_label': 'seats',
      'secondary_branding_desc': 'Secondary branding (e.g. Halal logo)',
      'secondary_logo_upload': 'Secondary Logo Upload',
      'security_access': 'Security & Access',
      'select_available_table': 'Select an available table',
      'select_booking_details': 'Select Booking Details',
      'select_date': 'Select Date',
      'select_date_range': 'Select Date Range',
      'select_end_date': 'Select End Date',
      'select_order_details': 'Select Order Details',
      'select_slot': 'Select Slot',
      'select_sound': 'Select Sound',
      'select_start_date': 'Select Start Date',
      'select_table': 'Select Table',
      'select_table_warning': 'Please select a table for this Dine-In order.',
      'select_waiter': 'Select Waiter',
      'select_waiter_warning': 'Please select a waiter for this order.',
      'send_test_email_btn': 'Send Test Email',
      'send_test_message': 'Send Test Message',
      'send_test_print': 'Send Test Print',
      'send_to_kitchen': 'SEND TO KITCHEN',
      'sender_number': 'Sender Number',
      'sending_test_email': 'Sending test email to',
      'sending_test_msg': 'Sending test message to',
      'sent_to_printer': 'Sent to Printer...',
      'server_error_retry': 'Server Error. Please try again.',
      'setting_updated_success': 'Setting updated successfully',
      'settings': 'Settings',
      'settings_not_loaded': 'Settings not loaded',
      'settings_updated_msg': 'Settings updated successfully!',
      'shift_label': 'Shift',
      'show_details': 'SHOW DETAILS',
      'smtp_config': 'SMTP Configuration',
      'smtp_host': 'SMTP Host',
      'smtp_pass': 'SMTP Password',
      'smtp_port': 'SMTP Port',
      'smtp_setup_desc': 'Configure your SMTP server to send automated emails.',
      'smtp_user': 'SMTP Username',
      'sound_desc': 'Enable/disable notification sounds',
      'sound_settings': 'Sound Settings',
      'special_requests': 'Special Requests / Notes',
      'split_bill': 'SPLIT BILL',
      'split_bill_dialog': 'Split Bill',
      'split_by': 'Split by',
      'staff_management': 'Staff Management',
      'staff_mgmt_desc': 'Manage your restaurant team and access levels',
      'staff_online': 'Staff Online',
      'staff_tab': 'STAFF',
      'start_new_order': 'Start New Order',
      'start_time_header': 'START TIME',
      'status_col': 'STATUS',
      'status_header': 'STATUS',
      'step_label': 'Step',
      'stock': 'Stock',
      'subtotal': 'Subtotal',
      'summary_tab': 'SUMMARY',
      'system_maintenance': 'System Maintenance',
      'system_reset': 'System Reset',
      'system_settings': 'System Settings',
      'system_update': 'System Update',
      'table': 'Table',
      'table_added_floor': 'Table added to floor plan',
      'table_label': 'Table',
      'table_layouts_settings': 'Table Layouts & Settings',
      'table_number': 'Table Number',
      'table_number_hint': 'Table Number (e.g. T15)',
      'table_qr_codes': 'Table QR Codes',
      'table_removed': 'Table removed successfully',
      'table_size': 'Table Size',
      'table_type': 'Table Type',
      'table_type_header': 'TABLE/TYPE',
      'table_updated': 'Table updated',
      'tables': 'Tables',
      'takeaway': 'Takeaway',
      'tax': 'Tax',
      'tax_rate_desc': 'Standard percentage for sales tax',
      'tax_rate_label': 'Tax Rate (%)',
      'taxes_gratuity': 'Taxes & Gratuity',
      'terminal': 'Terminal',
      'terminal_id': 'Terminal #',
      'test_connection': 'Test Connection',
      'test_email_address': 'Test Email Address',
      'test_email_desc': 'Enter an email address to send a test message.',
      'test_email_success': 'Success! Test email sent.',
      'test_failed': 'Connection Failed',
      'test_msg_desc': 'Enter a phone number to send a test message.',
      'test_msg_success': 'Success! Test message sent.',
      'test_phone_number': 'Test Phone Number',
      'test_print_sent': 'Test print sent!',
      'test_smtp_msg': 'Testing SMTP Configuration...',
      'test_sound': 'Test Sound',
      'test_success': 'Connection Successful!',
      'test_twilio_msg': 'Testing Twilio Configuration...',
      'thank_you_visiting': 'THANK YOU FOR VISITING!',
      'time_btn': 'TIME',
      'time_col': 'TIME',
      'time_label': 'Time',
      'tip': 'Tip',
      'tips_today': 'Tips (Today)',
      'today_reservations': 'Today Reservations',
      'todays_orders': 'Today\'s Orders',
      'todays_sale': 'Today\'s Sale',
      'top_selling_items': 'Top Selling Items (30 Days)',
      'total': 'Total',
      'total_bill': 'Total Bill',
      'total_col': 'TOTAL',
      'total_customers': 'Total Customers',
      'total_duration_header': 'TOTAL DURATION',
      'total_orders': 'TOTAL ORDERS',
      'transactional_reset_success': '',
      'try_different_date': 'Try a different date or time slot.',
      'twilio_config': 'Twilio Configuration',
      'twilio_setup_desc': '',
      'type_col': 'TYPE',
      'unit': 'Unit',
      'unpaid': 'Unpaid',
      'upcoming': 'Upcoming',
      'update_order': 'Update Order',
      'updating_order': 'Updating Order',
      'usb': 'USB',
      'user_created_success': 'User created successfully',
      'user_deleted_success': 'User deleted successfully',
      'user_management': 'User Management',
      'user_profile': 'User Profile',
      'user_updated_success': 'User updated successfully',
      'username': 'Username',
      'users_roles_permissions': 'Users, Roles & Permissions',
      'uses': 'uses',
      'variant': 'Variant',
      'version_label': 'Version',
      'view_details': 'View Details',
      'visit_time_prompt': 'When would you like to visit?',
      'visual_assets': 'Visual Assets',
      'waba_id': 'WABA ID (Business Account ID)',
      'waiting': 'Waiting',
      'waiting_status': 'Waiting',
      'website_order': 'Website Order',
      'whatsapp_phone': 'WhatsApp / Phone',
      'will_be_deleted': 'WILL BE DELETED',
      'will_be_preserved': 'WILL BE PRESERVED',
    },
    'Arabic': {
      '15_min_ago': 'منذ 15 دقيقة',
      '15_mins': '15 دقيقة',
      '1_day_ago': 'منذ يوم',
      '1_hour': 'ساعة واحدة',
      '1_hour_ago': 'منذ ساعة',
      '2_hours_ago': 'منذ ساعتين',
      '2_min_ago': 'منذ دقيقتين',
      '30_mins': '30 دقيقة',
      '5_mins': '5 دقائق',
      'account_sid': 'Account SID',
      'active_orders': 'الطلبات النشطة',
      'active_permissions': 'الأذونات النشطة',
      'active_tickets': 'تذاكر نشطة',
      'add_items_to_cart_warning': 'يرجى إضافة أصناف إلى السلة قبل المتابعة.',
      'add_new_booking': 'إضافة حجز جديد',
      'add_new_item': 'إضافة عنصر جديد',
      'add_new_staff': 'إضافة موظف جديد',
      'add_new_table': 'إضافة طاولة جديدة',
      'add_table': 'إضافة طاولة',
      'add_tip': 'إضافة بخشيش',
      'add_to_cart': 'أضف إلى السلة',
      'advance_booking_fee': 'رسوم الحجز المسبق',
      'advance_paid': 'مقدم مدفوع',
      'all': 'الكل',
      'all_caps': 'الكل',
      'all_items': 'كل الأصناف',
      'amount_due': 'المبلغ المستحق',
      'appetizers': 'مقبلات',
      'apply_discount': 'تطبيق الخصم',
      'are_you_sure': 'هل أنت متأكد تماماً؟',
      'assign_role': 'تعيين دور',
      'assign_table': 'تعيين طاولة',
      'attention': 'تنبيه',
      'aura_purple': 'أرجواني هالة',
      'auth_token': 'Auth Token',
      'auto_logout': 'تسجيل الخروج التلقائي',
      'auto_sync_active': 'المزامنة التلقائية نشطة (15 ث)',
      'available': 'متاح',
      'avg_counter_time': 'متوسط الوقت عند الكاونتر',
      'avg_order': 'متوسط الطلب',
      'avg_prep_time': 'متوسط وقت التحضير',
      'awaiting_payment': 'في انتظار الدفع',
      'back_btn': 'رجوع',
      'back_to_analytics': 'العودة إلى التحليلات',
      'back_to_dashboard': 'العودة إلى لوحة القيادة',
      'bluetooth': 'بلوتوث',
      'booking_fee': 'رسوم الحجز',
      'booking_fee_amount': 'مبلغ رسوم الحجز',
      'booking_fee_amount_desc': 'رسوم ثابتة لكل حجز',
      'branding': 'العلامة التجارية',
      'branding_desc': 'إدارة هويتك البصرية عبر POS والويب.',
      'browse_menu_desc': 'تصفح قائمة الطعام وأضفها إلى الطلب الحالي',
      'burger_patties_low': 'فطائر البرجر بدأت تنفد',
      'business_intelligence': 'ذكاء الأعمال',
      'cancel': 'إلغاء',
      'cancel_btn': 'إلغاء',
      'cancel_edit': 'إلغاء التعديل',
      'cancellation_rate': 'معدل الإلغاء',
      'cancelled': 'ملغي',
      'capacity': 'السعة',
      'capacity_label': 'السعة',
      'capacity_seats': 'السعة (مقاعد)',
      'card': 'بطاقة',
      'card_details': 'تفاصيل البطاقة',
      'card_number': 'رقم البطاقة',
      'card_terminal': 'بطاقة/جهاز',
      'cart_details': 'تفاصيل السلة',
      'cash': 'نقدي',
      'categories': 'الفئات',
      'category_created_success': 'تم إنشاء الفئة بنجاح',
      'category_deleted_success': 'تم حذف الفئة بنجاح',
      'category_failed_create': 'فشل في إنشاء الفئة',
      'category_updated_success': 'تم تحديث الفئة بنجاح',
      'chairs_count': 'عدد الكراسي #',
      'checkout': 'الدفع',
      'checkout_btn': 'الدفع',
      'choose_table': 'اختر طاولة',
      'clear_btn': 'مسح',
      'clear_filters': 'مسح التصفية',
      'clear_table': 'تفريغ الطاولة',
      'clear_takeaway': 'إلغاء / سفري',
      'clock_in_out': 'تسجيل الحضور/الانصراف',
      'clock_in_test': 'تسجيل دخول (موظف تجريبي)',
      'close': 'إغلاق',
      'close_btn': 'إغلاق',
      'collect_at_counter': 'تحصل من الضيف عند الكاونتر',
      'coming_soon': 'قريباً',
      'communications': 'اتصالات',
      'communications_desc': 'تكوين واتساب والرسائل والبريد الإلكتروني.',
      'complete_payment': 'إكمال الدفع',
      'completed': 'مكتمل',
      'completed_header': 'مكتمل',
      'configuration': 'إعداد',
      'confirm_payment': 'تأكيد الدفع',
      'confirm_rejection': 'تأكيد الرفض',
      'confirm_reservation': 'تأكيد الحجز',
      'confirm_reset': 'تأكيد إعادة الضبط',
      'confirm_split': 'تأكيد التقسيم',
      'confirmed': 'مؤكد',
      'conn_type': 'نوع الاتصال',
      'connection_error_msg': 'خطأ في الاتصال',
      'copy_link': 'نسخ الرابط',
      'counter_duration_header': 'مدة الكاونتر',
      'create_btn': 'إنشاء',
      'current_stock': 'المخزون الحالي',
      'custom_item': 'صنف مخصص',
      'customer_added_success': 'تم إضافة العميل بنجاح',
      'customer_deleted_success': 'تم حذف العميل بنجاح',
      'customer_directory': 'دليل العملاء',
      'customer_pickup': 'استلام العميل',
      'customer_pickup_desc': 'تفعيل خيار الاستلام على الموقع الإلكتروني',
      'customer_updated_success': 'تم تحديث العميل بنجاح',
      'customize_item': 'تخصيص',
      'cvc': 'CVC',
      'daily_deductions': 'الخصومات/الإضافات اليومية',
      'danger_zone': 'منطقة الخطر',
      'dark_mode': 'الوضع المظلم',
      'dark_mode_desc': 'التبديل بين الوضع المظلم والمضيء',
      'dashboard': 'لوحة القيادة',
      'data_impact_analysis': 'تحليل تأثير البيانات',
      'date_btn': 'التاريخ',
      'date_label': 'التاريخ',
      'date_range': 'نطاق التاريخ',
      'default_gratuity': 'نسبة البخشيش الافتراضية %',
      'default_gratuity_desc': 'رسوم خدمة تلقائية للمجموعات الكبيرة',
      'delete_btn': 'حذف',
      'delete_staff_q': 'حذف موظف؟',
      'delete_success': 'تم الحذف بنجاح',
      'delete_table': 'حذف الطاولة',
      'delete_table_confirm': 'هل أنت متأكد أنك تريد إزالة الطاولة',
      'delivery': 'توصيل',
      'demo_mode_desc': 'وضع العرض: عرض عينات من الأطباق المميزة',
      'desserts': 'حلويات',
      'detailed_orders_report': 'تقرير الطلبات المفصل',
      'dine_in': 'تناول هنا',
      'disabled': 'معطّل',
      'discount': 'الخصم',
      'discounts_label': 'خصومات',
      'each_person': 'لكل شخص',
      'edit': 'تعديل',
      'edit_item': 'تعديل العنصر',
      'edit_permissions_btn': 'تعديل الأذونات',
      'edit_permissions_title': 'تعديل الأذونات',
      'edit_staff_details': 'تعديل تفاصيل الموظف',
      'edit_table_details': 'تعديل تفاصيل الطاولة',
      'email_address': 'البريد الإلكتروني',
      'email_label': 'البريد الإلكتروني',
      'email_notifications': 'البريد الإلكتروني والتنبيهات',
      'emerald_green': 'أخضر زمردي',
      'empty_cart': 'سلة التسوق فارغة',
      'enable_booking_fee': 'تفعيل رسوم الحجز',
      'enable_booking_fee_desc': 'تحصيل رسوم من العملاء للحجوزات المسبقة',
      'enable_vat': 'تفعيل ضريبة القيمة المضافة',
      'enable_vat_desc': 'تطبيق حساب الضريبة التلقائي على إجمالي الطلبات',
      'enabled': 'مفعّل',
      'enter_capacity_warning': 'يرجى تحديد سعة الطاولة.',
      'enter_guest_name_warning': 'يرجى إدخال اسم الضيف.',
      'enter_guest_phone_warning': 'يرجى إدخال رقم هاتف الضيف.',
      'enter_table_number_warning': 'يرجى إدخال رقم الطاولة.',
      'environment': 'البيئة:',
      'environment_label': 'البيئة',
      'error_adding_customer': 'خطأ في إضافة العميل',
      'error_deleting_customer': 'خطأ في حذف العميل',
      'error_details': 'تفاصيل الخطأ',
      'error_label': 'خطأ',
      'error_loading_page': 'عذراً! حدث خطأ ما أثناء تحميل هذه الصفحة.',
      'error_updating_customer': 'خطأ في تحديث العميل',
      'est_profit': 'الربح التقديري',
      'expenses_purchases': 'المصاريف وطلبات الشراء',
      'expiry_date': 'تاريخ الانتهاء',
      'export_pdf': 'تصدير PDF',
      'extras_label': 'إضافات',
      'failed_to_delete': 'فشل في الحذف',
      'failed_to_load_inventory': 'فشل في تحميل المخزون',
      'failed_to_save': 'فشل في الحفظ',
      'failed_update_status': 'فشل تحديث الحالة',
      'favorites': 'المفضلة',
      'fee_policy_desc': '',
      'fill_guest_details_warning': 'يرجى تقديم الاسم ورقم الهاتف للمتابعة.',
      'filter_by_status': 'تصفية حسب الحالة',
      'filter_by_type': 'تصفية حسب النوع',
      'first_name': 'الاسم الأول',
      'food_items': 'أصناف الطعام',
      'food_management': 'إدارة الطعام',
      'free_status': 'شاغر',
      'from_email': 'من البريد الإلكتروني',
      'from_label': 'من',
      'from_name': 'اسم المرسل',
      'full_name': 'الاسم الكامل',
      'general': 'عام',
      'general_settings': 'الإعدادات العامة',
      'general_settings_desc': 'تكوين هوية المطعم والتفضيلات الأساسية.',
      'guest_prompt': 'أخبرنا عن الضيف',
      'guests': 'ضيوف',
      'guests_btn': 'الضيوف',
      'guests_label': 'الضيوف',
      'home_delivery': 'توصيل منزلي',
      'home_delivery_desc': 'تفعيل خيار التوصيل على الموقع الإلكتروني',
      'human_resource': 'الموارد البشرية',
      'id_col': 'المعرف',
      'interactive_floor_plan': 'خريطة الطوابق التفاعلية',
      'interface_theme': 'سمة الواجهة',
      'interface_theme_desc': 'النمط البصري لجميع واجهات الطرفية',
      'invalid_ip_format': 'تنسيق عنوان IP غير صالح',
      'inventory_management': 'إدارة المخزون',
      'item': 'الصنف',
      'item_added': 'تمت إضافة الصنف إلى السلة',
      'item_name': 'اسم العنصر',
      'item_removed_order': 'تمت إزالة الصنف من الطلب.',
      'items_header': 'الأصناف',
      'kds': 'نظام شاشة المطبخ',
      'kds_timer': 'مؤقت تحذير KDS',
      'kds_timer_desc': 'دقائق قبل تمييز الطلب كمتأخر',
      'kitchen_alert': 'تنبيه المطبخ',
      'kitchen_bookings': 'المطبخ والحجوزات',
      'kitchen_production': 'إنتاج المطبخ',
      'lang_desc': 'تغيير لغة التطبيق',
      'lang_settings': 'إعدادات اللغة',
      'language': 'اللغة',
      'last_name': 'اسم العائلة',
      'legal_name': 'الاسم القانوني',
      'legal_name_desc': 'يظهر على الإيصالات والمستندات القانونية',
      'lifecycle_tracking': 'تتبع دورة الحياة من الطلب إلى الخدمة',
      'lifetime_orders': 'إجمالي الطلبات',
      'link_copied_for': 'تم نسخ الرابط لـ',
      'live_bookings': 'الحجوزات المباشرة',
      'live_data_sync': '',
      'live_order_feed': 'تغذية الطلبات الحية',
      'logout_desc': 'ضبط وقت تسجيل الخروج التلقائي',
      'logout_not_connected': 'وظيفة تسجيل الخروج غير متصلة',
      'low_stock_alert': 'تنبيه انخفاض المخزون',
      'main_brand_logo_desc': 'شعار العلامة التجارية الرئيسي المعروض في الرأس',
      'main_course': 'طبق رئيسي',
      'main_course_items': 'الأطباق الرئيسية',
      'manage_active_order': 'إدارة الطلب النشط',
      'manager_dashboard': 'لوحة تحكم المدير',
      'manual_status_override': 'تجاوز الحالة يدويًا',
      'mark_all_read': 'تحديد الكل كمقروء',
      'mark_as_read': 'تمييز كمقروء',
      'menu_item_created_success': 'تم إنشاء صنف القائمة بنجاح',
      'menu_item_deleted_success': 'تم حذف صنف القائمة بنجاح',
      'menu_item_updated_success': 'تم تحديث صنف القائمة بنجاح',
      'menu_items_categories': 'أصناف القائمة والفئات',
      'messages_inquiries': 'الرسائل والاستفسارات',
      'messaging_integration': 'تكامل المراسلة',
      'midnight_blue': 'أزرق داكن',
      'min': 'الحد الأدنى',
      'min_stock_level': 'مستوى الحد الأدنى',
      'mission_control': 'مركز التحكم',
      'monthly_revenue_trend': 'الإيرادات الشهرية - اتجاه 6 أشهر',
      'name_phone_required': 'الاسم والهاتف مطلوبان',
      'needs_clearing': 'بحاجة لتنظيف',
      'net_sales': 'صافي المبيعات',
      'network': 'الشبكة',
      'never': 'أبداً',
      'new_order_received': 'تم استلام طلب جديد',
      'next_btn': 'التالي',
      'no_data': 'لا توجد بيانات',
      'no_items_desc': 'لا توجد أصناف بعد. اضغط على بطاقة القائمة للإضافة.',
      'no_kds_orders': 'لا توجد طلبات نشطة في المطبخ',
      'no_messages_yet': 'لا توجد رسائل بعد',
      'no_orders_in': 'لا توجد طلبات في حالة',
      'no_reservations_found': 'لم يتم العثور على حجوزات',
      'no_results_found': 'لم يتم العثور على نتائج',
      'no_sales_data': 'لا توجد بيانات مبيعات',
      'no_shift_data': 'لا توجد بيانات ورديات متاحة لليوم',
      'no_tables_available': 'لا توجد طاولات متاحة',
      'no_tables_found': 'لم يتم العثور على طاولات',
      'no_users_found': 'لم يتم العثور على مستخدمين.',
      'notification_settings': 'إعدادات التنبيهات',
      'notification_volume': 'مستوى صوت التنبيه',
      'notifications': 'التنبيهات',
      'occupied': 'مشغول',
      'occupied_status': 'مشغول',
      'of_label': 'من',
      'official_receipt': 'إيصال رسمي',
      'ok': 'موافق',
      'online_order': 'طلب إلكتروني',
      'operational_analytics': 'التحليلات التشغيلية',
      'operational_controls': 'الضبط التشغيلي',
      'operational_controls_desc': 'إدارة الضرائب والرسوم وسلوك الأتمتة.',
      'operational_status': 'الحالة التشغيلية',
      'operations': 'عمليات',
      'order_channels': 'قنوات الطلب',
      'order_id': 'رقم الطلب #',
      'order_marked_status': 'تم تمييز الطلب كـ',
      'order_notifications': 'تنبيهات الطلبات',
      'order_notifications_desc': 'تشغيل صوت عند وصول طلب جديد',
      'order_num_header': 'رقم الطلب #',
      'order_payment': 'دفع الطلب',
      'order_placed_success': 'تم تقديم الطلب بنجاح! أرسل إلى KDS.',
      'order_ready_pickup': 'الطلب جاهز للاستلام',
      'order_service_split': 'توزيع نوع الخدمة',
      'order_type': 'نوع الطلب',
      'order_updated_success': 'تم تحديث الطلب بنجاح!',
      'order_velocity_analytics': 'تحليلات سرعة الطلب',
      'orders': 'الطلبات',
      'orders_in_view': 'الطلبات المعروضة',
      'orders_management': 'إدارة الطلبات',
      'orders_payments_reservations': 'الطلبات والمدفوعات والحجوزات',
      'out_of_stock': 'نفذ من المخزون',
      'paid': 'مدفوع',
      'password': 'كلمة المرور',
      'pax_label': 'شخص',
      'pay_all': 'دفع الكل',
      'pay_first': 'دفع أولاً',
      'pay_last': 'دفع آخراً',
      'pay_now': 'ادفع الآن',
      'payment_method_coverage': 'تغطية طريقة الدفع',
      'payment_policy': 'سياسة الدفع',
      'payment_policy_desc': '',
      'payment_processed': 'تمت معالجة الدفع',
      'payment_success_message': 'تمت معالجة الدفع بنجاح!',
      'payments': 'مدفوعات',
      'pending': 'قيد الانتظار',
      'pending_orders_kds': 'الطلبات قيد الانتظار (KDS)',
      'people': 'أشخاص',
      'people_label': 'أشخاص',
      'permissions_updated': 'تم تحديث الأذونات',
      'pers_label': 'شخص',
      'phone_label': 'الهاتف',
      'pick_up': 'استلام',
      'pickup': 'استلام',
      'please_select_table': 'يرجى اختيار طاولة',
      'popular_customizations': 'الإضافات الأكثر شعبية',
      'pos': 'نقطة البيع',
      'pos_system_updated': 'تم تحديث نظام نقطة البيع بنجاح',
      'powered_by_stripe': 'بدعم من Stripe',
      'preparing': 'قيد التحضير',
      'price': 'السعر',
      'primary_currency': 'العملة الرئيسية',
      'primary_currency_desc': 'جميع المعاملات المالية ستستخدم هذه',
      'primary_logo_upload': 'تحميل الشعار الرئيسي',
      'print': 'طباعة',
      'print_all_qr': 'طباعة جميع رموز QR',
      'print_now': 'طباعة الآن',
      'printer_desc': 'تكوين طابعة الفواتير',
      'printer_ip': 'عنوان IP للطابعة',
      'printer_settings': 'إعدادات الطابعة',
      'product_mix_tab': 'مزيج المنتجات',
      'production': 'الإنتاج',
      'provide_rejection_reason': 'يرجى تقديم سبب لرفض الطلب',
      'purchase_inventory_hub': 'مركز المشتريات والمخزون',
      'purchase_management': 'إدارة المشتريات',
      'qr_menu_order': 'طلب قائمة QR',
      'qr_table_ordering': 'طلب طاولة QR',
      'qr_table_ordering_desc': 'السماح للعملاء بالطلب عبر رموز QR',
      'qty': 'الكمية',
      'quick_clock_in_test': 'تسجيل دخول سريع للاختبار',
      'ready': 'جاهز',
      'reason_required': 'السبب مطلوب',
      'received_at': 'تم الاستلام في',
      'recent': 'الأخيرة',
      'recent_activity': 'النشاط الأخير',
      'recent_transactions': 'المعاملات الأخيرة',
      'reject_order': 'رفض الطلب',
      'rejected': 'مرفوض',
      'rejection_reason_hint': 'مثال: نفذ من المخزون، المطبخ مشغول جداً...',
      'remove_user_confirm': 'هل أنت متأكد أنك تريد إزالة المستخدم من النظام؟',
      'reports': 'التقارير',
      'reservation': 'الحجز',
      'reservation_failed': 'فشل في إنشاء الحجز',
      'reservation_success': 'تم إنشاء الحجز بنجاح!',
      'reservation_summary': 'ملخص الحجز',
      'reservations': 'الحجوزات',
      'reserved': 'محجوز',
      'reset_confirmation_detailed': '',
      'reset_transactional_data': 'إعادة ضبط بيانات المعاملات',
      'reset_transactional_data_desc': '',
      'reset_warning_text': '',
      'restaurant_info': 'معلومات المطعم',
      'retry': 'إعادة المحاولة',
      'retry_fetch': 'إعادة المحاولة',
      'review_confirm': 'المراجعة والتأكيد',
      'role_admin': 'الدور: مدير',
      'role_permissions': 'الأدوار والأذونات',
      'roles_desc': 'تكوين مستويات الوصول لكل دور وظيفي',
      'roles_permissions_title': 'الأدوار والأذونات',
      'sales_log_tab': 'سجل المبيعات',
      'save': 'حفظ',
      'save_btn': 'حفظ',
      'save_changes': 'حفظ التغييرات',
      'save_item': 'حفظ العنصر',
      'save_settings': 'حفظ الإعدادات',
      'save_success': 'تم الحفظ بنجاح',
      'search_items': 'ابحث عن أصناف...',
      'search_orders': 'البحث في الطلبات',
      'search_table': 'ابحث عن رقم الطاولة...',
      'seat_guest': 'إجلاس الضيف',
      'seated': 'جالس',
      'seats_label': 'مقاعد',
      'secondary_branding_desc': 'العلامة التجارية الثانوية (مثلاً شعار حلال)',
      'secondary_logo_upload': 'تحميل الشعار الثانوي',
      'security_access': 'الأمن والوصول',
      'select_available_table': 'اختر طاولة متاحة',
      'select_booking_details': 'اختر حجزًا لعرض التفاصيل',
      'select_date': 'اختر التاريخ',
      'select_date_range': 'اختر نطاق التاريخ',
      'select_end_date': 'اختر تاريخ الانتهاء',
      'select_order_details': 'اختر طلبًا لعرض التفاصيل',
      'select_slot': 'اختر موعداً',
      'select_sound': 'اختر الصوت',
      'select_start_date': 'اختر تاريخ البدء',
      'select_table': 'اختر الطاولة',
      'select_table_warning': 'يرجى اختيار طاولة لهذا الطلب.',
      'select_waiter': 'اختر النادل',
      'select_waiter_warning': 'يرجى اختيار نادل لهذا الطلب.',
      'send_test_email_btn': 'إرسال بريد تجريبي',
      'send_test_message': 'إرسال رسالة تجريبية',
      'send_test_print': 'إرسال طباعة تجريبية',
      'send_to_kitchen': 'إرسال للمطبخ',
      'sender_number': 'رقم المرسل',
      'sending_test_email': 'جاري إرسال بريد تجريبي إلى',
      'sending_test_msg': 'جاري إرسال رسالة تجريبية إلى',
      'sent_to_printer': 'تم الإرسال للطابعة...',
      'server_error_retry': 'خطأ في الخادم. يرجى المحاولة مرة أخرى.',
      'setting_updated_success': 'تم تحديث الإعداد بنجاح',
      'settings': 'الإعدادات',
      'settings_not_loaded': 'لم يتم تحميل الإعدادات',
      'settings_updated_msg': 'تم تحديث الإعدادات بنجاح!',
      'shift_label': 'الوردية',
      'show_details': 'عرض التفاصيل',
      'smtp_config': 'إعدادات SMTP',
      'smtp_host': 'SMTP Host',
      'smtp_pass': 'كلمة المرور (SMTP)',
      'smtp_port': 'SMTP Port',
      'smtp_setup_desc': '',
      'smtp_user': 'اسم المستخدم (SMTP)',
      'sound_desc': 'تفعيل/تعطيل أصوات التنبيه',
      'sound_settings': 'إعدادات الصوت',
      'special_requests': 'طلبات خاصة / ملاحظات',
      'split_bill': 'تقسيم الفاتورة',
      'split_bill_dialog': 'تقسيم الفاتورة',
      'split_by': 'تقسيم على',
      'staff_management': 'إدارة الموظفين',
      'staff_mgmt_desc': 'إدارة فريق المطعم ومستويات الوصول',
      'staff_online': 'الموظفون المتصلون',
      'staff_tab': 'الموظفين',
      'start_new_order': 'بدء طلب جديد',
      'start_time_header': 'وقت البدء',
      'status_col': 'الحالة',
      'status_header': 'الحالة',
      'step_label': 'خطوة',
      'stock': 'المخزون',
      'subtotal': 'المجموع الفرعي',
      'summary_tab': 'الملخص',
      'system_maintenance': 'صيانة النظام',
      'system_reset': 'إعادة ضبط النظام',
      'system_settings': 'إعدادات النظام',
      'system_update': 'تحديث النظام',
      'table': 'طاولة',
      'table_added_floor': 'تمت إضافة الطاولة إلى مخطط الأرضية',
      'table_label': 'طاولة',
      'table_layouts_settings': 'تخطيطات الطاولات والإعدادات',
      'table_number': 'رقم الطاولة',
      'table_number_hint': 'رقم الطاولة (مثال: T15)',
      'table_qr_codes': 'رموز QR للطاولات',
      'table_removed': 'تمت إزالة الطاولة بنجاح',
      'table_size': 'حجم الطاولة',
      'table_type': 'نوع الطاولة',
      'table_type_header': 'الطاولة/النوع',
      'table_updated': 'تم تحديث الطاولة',
      'tables': 'الطاولات',
      'takeaway': 'سفري',
      'tax': 'الضريبة',
      'tax_rate_desc': 'النسبة المئوية القياسية لضريبة المبيعات',
      'tax_rate_label': 'معدل الضريبة (%)',
      'taxes_gratuity': 'الضرائب والبخشيش',
      'terminal': 'المحطة',
      'terminal_id': 'المحطة #',
      'test_connection': 'اختبار الاتصال',
      'test_email_address': 'عنوان البريد التجريبي',
      'test_email_desc': 'أدخل عنوان البريد الإلكتروني لإرسال رسالة تجريبية.',
      'test_email_success': 'تم! تم إرسال البريد التجريبي.',
      'test_failed': 'فشل الاختبار',
      'test_msg_desc': 'أدخل رقم الهاتف لإرسال رسالة تجريبية.',
      'test_msg_success': 'تم! تم إرسال الرسالة التجريبية.',
      'test_phone_number': 'رقم الهاتف التجريبي',
      'test_print_sent': 'تم إرسال طباعة تجريبية!',
      'test_smtp_msg': 'بريد اختبار SMTP',
      'test_sound': 'تجربة الصوت',
      'test_success': 'تم بنجاح',
      'test_twilio_msg': 'رسالة اختبار Twilio',
      'thank_you_visiting': 'شكراً لزيارتكم!',
      'time_btn': 'الوقت',
      'time_col': 'الوقت',
      'time_label': 'الوقت',
      'tip': 'بخشيش',
      'tips_today': 'البخشيش (اليوم)',
      'today_reservations': 'حجوزات اليوم',
      'todays_orders': 'طلبات اليوم',
      'todays_sale': 'مبيعات اليوم',
      'top_selling_items': 'الأصناف الأكثر مبيعاً (30 يوماً)',
      'total': 'المجموع',
      'total_bill': 'إجمالي الفاتورة',
      'total_col': 'الإجمالي',
      'total_customers': 'إجمالي العملاء',
      'total_duration_header': 'المدة الإجمالية',
      'total_orders': 'إجمالي الطلبات',
      'transactional_reset_success': 'تمت إعادة ضبط بيانات المعاملات بنجاح.',
      'try_different_date': 'جرب تاريخاً أو وقتاً مختلفاً.',
      'twilio_config': 'إعدادات Twilio',
      'twilio_setup_desc': 'تكوين Twilio لتنبيهات واتساب والرسائل النصية.',
      'type_col': 'النوع',
      'unit': 'الوحدة',
      'unpaid': 'غير مدفوع',
      'upcoming': 'قادم',
      'update_order': 'Update Order',
      'updating_order': 'تحديث الطلب',
      'usb': 'USB',
      'user_created_success': 'تم إنشاء المستخدم بنجاح',
      'user_deleted_success': 'تم حذف المستخدم بنجاح',
      'user_management': 'إدارة المستخدمين',
      'user_profile': 'ملف المستخدم',
      'user_updated_success': 'تم تحديث المستخدم بنجاح',
      'username': 'اسم المستخدم',
      'users_roles_permissions': 'المستخدمون والأدوار والأذونات',
      'uses': 'استخدامات',
      'variant': 'نوع',
      'version_label': 'الإصدار',
      'view_details': 'عرض التفاصيل',
      'visit_time_prompt': 'متى تود زيارتنا؟',
      'visual_assets': 'الأصول البصرية',
      'waba_id': 'WABA ID',
      'waiting': 'انتظار',
      'waiting_status': 'في الانتظار',
      'website_order': 'طلب الموقع',
      'whatsapp_phone': 'واتساب / الهاتف',
      'will_be_deleted': 'سيتم حذفها',
      'will_be_preserved': 'سيتم الحفاظ عليها',
    },
    'Urdu': {
      '15_min_ago': '15 منٹ پہلے',
      '15_mins': '15 منٹ',
      '1_day_ago': '1 دن پہلے',
      '1_hour': '1 گھنٹہ',
      '1_hour_ago': '1 گھنٹہ پہلے',
      '2_hours_ago': '2 گھنٹے پہلے',
      '2_min_ago': '2 منٹ پہلے',
      '30_mins': '30 منٹ',
      '5_mins': '5 منٹ',
      'account_sid': 'اکاؤنٹ SID',
      'active_orders': 'فعال آرڈرز',
      'active_permissions': 'فعال اجازتیں',
      'active_tickets': 'فعال ٹکٹ',
      'add_items_to_cart_warning': 'براہ کرم کارٹ میں اشیاء شامل کریں۔',
      'add_new_booking': 'نئی بکنگ شامل کریں',
      'add_new_item': 'نیا آئٹم شامل کریں',
      'add_new_staff': 'نیا اسٹاف شامل کریں',
      'add_new_table': 'Add New Table',
      'add_table': 'ٹیبل شامل کریں',
      'add_tip': 'ٹپ شامل کریں',
      'add_to_cart': 'کارٹ میں شامل کریں',
      'advance_booking_fee': 'ایڈوانس بکنگ فیس',
      'advance_paid': 'ایڈوانس ادا کیا گیا',
      'all': 'تمام',
      'all_caps': 'سب',
      'all_items': 'تمام اشیاء',
      'amount_due': 'واجب الادا رقم',
      'appetizers': 'سٹارٹرز',
      'apply_discount': 'رعایت لاگو کریں',
      'are_you_sure': 'کیا آپ کو یقین ہے؟',
      'assign_role': 'کردار تفویض کریں',
      'assign_table': 'ٹیبل تفویض کریں',
      'attention': 'توجہ',
      'aura_purple': 'ارغوانی',
      'auth_token': 'آتھ ٹوکن',
      'auto_logout': 'آٹو لاگ آؤٹ',
      'auto_sync_active': 'خودکار مطابقت فعال ہے (15s)',
      'available': 'دستیاب',
      'avg_counter_time': 'کاؤنٹر کا اوسط وقت',
      'avg_order': 'اوسط آرڈر',
      'avg_prep_time': 'تیاری کا اوسط وقت',
      'awaiting_payment': 'ادائیگی کا انتظار',
      'back_btn': 'پیچھے',
      'back_to_analytics': 'اینالیٹکس پر واپس جائیں',
      'back_to_dashboard': 'ڈیش بورڈ پر واپس جائیں',
      'bluetooth': 'بلوٹوتھ',
      'booking_fee': 'بکنگ فیس',
      'booking_fee_amount': 'بکنگ فیس کی رقم',
      'booking_fee_amount_desc': 'فی ریزرویشن مقررہ فیس',
      'branding': 'برانڈنگ',
      'branding_desc': 'POS اور ویب پر اپنی بصری شناخت کا انتظام کریں.',
      'browse_menu_desc': '',
      'burger_patties_low': 'برگر پیٹیز کم ہو رہی ہیں',
      'business_intelligence': 'بزنس انٹیلی جنس',
      'cancel': 'منسوخ کریں',
      'cancel_btn': 'منسوخ کریں',
      'cancel_edit': 'ترمیم منسوخ کریں',
      'cancellation_rate': 'منسوخی کی شرح',
      'cancelled': 'منسوخ',
      'capacity': 'گنجائش',
      'capacity_label': 'گنجائش',
      'capacity_seats': 'گنجائش (نشستیں)',
      'card': 'کارڈ',
      'card_details': 'کارڈ کی تفصیلات',
      'card_number': 'کارڈ نمبر',
      'card_terminal': 'کارڈ/ٹرمینل',
      'cart_details': 'کارٹ کی تفصیلات',
      'cash': 'نقد',
      'categories': 'اقسام',
      'category_created_success': 'کیٹیگری کامیابی سے بن گئی ہے',
      'category_deleted_success': 'کیٹیگری کامیابی سے حذف ہو گئی',
      'category_failed_create': 'کیٹیگری بنانے میں ناکامی',
      'category_updated_success': 'کیٹیگری کامیابی سے اپ ڈیٹ ہو گئی',
      'chairs_count': 'کرسیاں #',
      'checkout': 'چیک آؤٹ',
      'checkout_btn': 'چیک آؤٹ',
      'choose_table': 'ٹیبل منتخب کریں',
      'clear_btn': 'صاف کریں',
      'clear_filters': 'فلٹر صاف کریں',
      'clear_table': 'ٹیبل خالی کریں',
      'clear_takeaway': 'کلیئر / ٹیک اوے',
      'clock_in_out': 'کلاک ان/آؤٹ',
      'clock_in_test': 'کلاک ان (جان اسٹاف)',
      'close': 'بند کریں',
      'close_btn': 'بند کریں',
      'collect_at_counter': 'کاؤنٹر پر مہمان سے وصول کریں',
      'coming_soon': 'جلد آ رہا ہے',
      'communications': 'رابطہ',
      'communications_desc': 'واٹس اپ، SMS اور ای میل ترتیب کریں.',
      'complete_payment': 'ادائیگی مکمل کریں',
      'completed': 'مکمل',
      'completed_header': 'مکمل',
      'configuration': 'ترتیبات',
      'confirm_payment': 'ادائیگی کی تصدیق کریں',
      'confirm_rejection': 'مسترد کرنے کی تصدیق کریں',
      'confirm_reservation': 'ریزرویشن کی تصدیق کریں',
      'confirm_reset': 'ری سیٹ کی تصدیق کریں',
      'confirm_split': 'تقسیم کی تصدیق کریں',
      'confirmed': 'تصدیق شدہ',
      'conn_type': 'کنکشن کی قسم',
      'connection_error_msg': 'کنکشن کی خرابی',
      'copy_link': 'لنک کاپی کریں',
      'counter_duration_header': 'کاؤنٹر کا دورانیہ',
      'create_btn': 'بنائیں',
      'current_stock': 'موجودہ اسٹاک',
      'custom_item': 'کسٹم آئٹم',
      'customer_added_success': 'کسٹمر کامیابی سے شامل ہو گیا',
      'customer_deleted_success': 'کسٹمر کامیابی سے حذف ہو گیا',
      'customer_directory': 'صارفین کی ڈائریکٹری',
      'customer_pickup': 'کسٹمر پک اپ',
      'customer_pickup_desc': 'ویب سائٹ پر پک اپ کا آپشن فعال کریں',
      'customer_updated_success': 'کسٹمر کامیابی سے اپ ڈیٹ ہو گیا',
      'customize_item': 'اپنی مرضی سے بنائیں',
      'cvc': 'CVC',
      'daily_deductions': 'یومیہ کٹوتیاں/اضافے',
      'danger_zone': 'خطرہ زون',
      'dark_mode': 'ڈارک موڈ',
      'dark_mode_desc': 'لائٹ اور ڈارک تھیم کے درمیان سوئچ کریں',
      'dashboard': 'ڈیش بورڈ',
      'data_impact_analysis': 'ڈیٹا اثر تجزیہ',
      'date_btn': 'تاریخ',
      'date_label': 'تاریخ',
      'date_range': 'تاریخ کی حد',
      'default_gratuity': 'ڈیفالٹ ٹپ %',
      'default_gratuity_desc': 'بڑے گروپس کے لیے خودکار سروس چارج',
      'delete_btn': 'حذف کریں',
      'delete_staff_q': 'اسٹاف حذف کریں؟',
      'delete_success': 'کامیابی سے حذف ہو گیا',
      'delete_table': 'ٹیبل حذف کریں',
      'delete_table_confirm': 'کیا آپ واقعی ٹیبل ہٹانا چاہتے ہیں',
      'delivery': 'ڈیلیوری',
      'demo_mode_desc': 'ڈیمو موڈ: نمونہ دستخطی اشیاء دکھا رہا ہے',
      'desserts': 'میٹٹھا',
      'detailed_orders_report': 'تفصیلی آرڈر رپورٹ',
      'dine_in': 'ڈائن ان',
      'disabled': 'غیر فعال',
      'discount': 'رعایت',
      'discounts_label': 'رعایت',
      'each_person': 'فی شخص',
      'edit': 'ترمیم',
      'edit_item': 'آئٹم ترمیم کریں',
      'edit_permissions_btn': 'اجازتیں ترمیم کریں',
      'edit_permissions_title': 'اجازتیں ترمیم کریں',
      'edit_staff_details': 'اسٹاف کی تفصیلات ترمیم کریں',
      'edit_table_details': 'ٹیبل کی تفصیلات ایڈٹ کریں',
      'email_address': 'ای میل ایڈریس',
      'email_label': 'ای میل',
      'email_notifications': 'ای میل اور اطلاعات',
      'emerald_green': 'زمرد سبز',
      'empty_cart': 'آپ کا کارٹ خالی ہے',
      'enable_booking_fee': 'بکنگ فیس فعال کریں',
      'enable_booking_fee_desc': 'پیشگی ریزرویشن کے لیے صارفین سے چارج کریں',
      'enable_vat': 'VAT/ٹیکس فعال کریں',
      'enable_vat_desc': 'آرڈر کے مجموعی پر خودکار ٹیکس کا اطلاق کریں',
      'enabled': 'فعال',
      'enter_capacity_warning': 'براہ کرم گنجائش درج کریں۔',
      'enter_guest_name_warning': 'براہ کرم مہمان کا نام درج کریں۔',
      'enter_guest_phone_warning': 'براہ کرم فون نمبر درج کریں۔',
      'enter_table_number_warning': 'براہ کرم ٹیبل نمبر درج کریں۔',
      'environment': 'ماحول:',
      'environment_label': 'انوائرمنٹ',
      'error_adding_customer': 'کسٹمر شامل کرنے میں غلطی',
      'error_deleting_customer': 'کسٹمر حذف کرنے میں غلطی',
      'error_details': 'غلطی کی تفصیلات',
      'error_label': 'غلطی',
      'error_loading_page': 'اوہ! اس صفحہ کو لوڈ کرنے میں کچھ غلط ہو گیا ہے۔',
      'error_updating_customer': 'کسٹمر اپ ڈیٹ کرنے میں غلطی',
      'est_profit': 'تخمینہ منافع',
      'expenses_purchases': 'اخراجات اور خریداری کے آرڈرز',
      'expiry_date': 'خاتمے کی تاریخ',
      'export_pdf': 'پی ڈی ایف ایکسپورٹ کریں',
      'extras_label': 'اضافی',
      'failed_to_delete': 'حذف کرنے میں ناکامی',
      'failed_to_load_inventory': 'انوینٹری لوڈ کرنے میں ناکامی',
      'failed_to_save': 'ترتیبات محفوظ کرنے میں ناکامی',
      'failed_update_status': 'حالت اپ ڈیٹ کرنے میں ناکامی',
      'favorites': 'پسندیدہ',
      'fee_policy_desc': '',
      'fill_guest_details_warning': 'براہ کرم مہمان کی تفصیلات پُر کریں۔',
      'filter_by_status': 'حالت کے لحاظ سے فلٹر کریں',
      'filter_by_type': 'قسم کے لحاظ سے فلٹر کریں',
      'first_name': 'پہلا نام',
      'food_items': 'کھانے کی اشیاء',
      'food_management': 'فوڈ مینجمنٹ',
      'free_status': 'خالی',
      'from_email': 'ای میل سے',
      'from_label': 'سے',
      'from_name': 'بھیجنے والے کا نام',
      'full_name': 'پورا نام',
      'general': 'عام',
      'general_settings': 'عمومی ترتیبات',
      'general_settings_desc': '',
      'guest_prompt': 'مہمان کے بارے میں بتائیں',
      'guests': 'مہمان',
      'guests_btn': 'مہمانوں',
      'guests_label': 'مہمانوں',
      'home_delivery': 'ہوم ڈیلیوری',
      'home_delivery_desc': 'ویب سائٹ پر ڈیلیوری کا آپشن فعال کریں',
      'human_resource': 'انسانی وسائل',
      'id_col': 'آئی ڈی',
      'interactive_floor_plan': 'Interactive Floor Plan',
      'interface_theme': 'انٹرفیس تھیم',
      'interface_theme_desc': 'تمام ٹرمینل انٹرفیسز کا بصری انداز',
      'invalid_ip_format': 'آئی پی ایڈریس فارمیٹ درست نہیں ہے',
      'inventory_management': 'انوینٹری مینجمنٹ',
      'item': 'آئٹم',
      'item_added': 'آئٹم کارٹ میں شامل ہو گیا',
      'item_name': 'آئٹم کا نام',
      'item_removed_order': 'آئٹم آرڈر سے ہٹا دیا گیا۔',
      'items_header': 'اشیاء',
      'kds': 'کچن ڈسپلے سسٹم',
      'kds_timer': 'KDS وارننگ ٹائمر',
      'kds_timer_desc': 'آرڈر کے تاخیر سے نشان زد ہونے سے پہلے کے منٹ',
      'kitchen_alert': 'کچن الرٹ',
      'kitchen_bookings': 'کچن اور بکنگز',
      'kitchen_production': 'کچن پروڈکشن',
      'lang_desc': 'ایپ کی زبان تبدیل کریں',
      'lang_settings': 'زبان کی ترتیبات',
      'language': 'زبان',
      'last_name': 'آخری نام',
      'legal_name': 'قانونی نام',
      'legal_name_desc': 'رسیدوں اور قانونی دستاویزات پر دکھائی جاتی ہے',
      'lifecycle_tracking': 'آرڈر سے سروس تک لائف سائیکل ٹریکنگ',
      'lifetime_orders': 'کل آرڈرز',
      'link_copied_for': 'لنک کاپی کر لیا گیا برائے',
      'live_bookings': 'لائیو بکنگ',
      'live_data_sync': 'آن لائن آرڈرز اور ریزرویشن کے ساتھ لائیو ڈیٹا مطابقت',
      'live_order_feed': 'لائیو آرڈر فیڈ',
      'logout_desc': 'آٹو لاگ آؤٹ کا وقت مقرر کریں',
      'logout_not_connected': 'لاگ آؤٹ کی فعالیت منسلک نہیں ہے',
      'low_stock_alert': 'اسٹاک کم ہونے کی اطلاع',
      'main_brand_logo_desc': 'ہیڈر میں دکھایا جانے والا مین برانڈ لوگو',
      'main_course': 'مین کورس',
      'main_course_items': 'مین کورس آئٹمز',
      'manage_active_order': 'فعال آرڈر کا انتظام کریں',
      'manager_dashboard': 'مینیجر ڈیش بورڈ',
      'manual_status_override': 'حالت کو دستی طور پر تبدیل کریں',
      'mark_all_read': 'تمام پڑھے ہوئے نشان زد کریں',
      'mark_as_read': 'پڑھا ہوا نشان زد کریں',
      'menu_item_created_success': 'مینو آئٹم کامیابی سے بن گیا ہے',
      'menu_item_deleted_success': 'مینو آئٹم کامیابی سے حذف ہو گیا',
      'menu_item_updated_success': 'مینو آئٹم کامیابی سے اپ ڈیٹ ہو گیا',
      'menu_items_categories': 'مینو آئٹمز اور زمرے',
      'messages_inquiries': 'پیغامات اور پوچھ گچھ',
      'messaging_integration': 'میسجنگ انٹیگریشن',
      'midnight_blue': 'مڈ نائٹ بلیو',
      'min': 'کم سے کم',
      'min_stock_level': 'کم سے کم اسٹاک لیول',
      'mission_control': 'مشن کنٹرول',
      'monthly_revenue_trend': 'ماہانہ آمدنی - 6 ماہ کا رجحان',
      'name_phone_required': 'نام اور فون نمبر ضروری ہیں',
      'needs_clearing': 'صفائی کی ضرورت ہے',
      'net_sales': 'کل فروخت',
      'network': 'نیٹ ورک',
      'never': 'کبھی نہیں',
      'new_order_received': 'نیا آرڈر موصول ہوا',
      'next_btn': 'اگلا',
      'no_data': 'کوئی ڈیٹا نہیں ہے',
      'no_items_desc': '',
      'no_kds_orders': 'کچن میں کوئی فعال آرڈر نہیں ہے۔',
      'no_messages_yet': 'ابھی تک کوئی پیغام نہیں ہے',
      'no_orders_in': 'میں کوئی آرڈر نہیں ہے',
      'no_reservations_found': 'کوئی تحفظات نہیں ملے',
      'no_results_found': 'کوئی نتائج نہیں ملے',
      'no_sales_data': 'سیلز کا کوئی ڈیٹا نہیں ہے',
      'no_shift_data': 'آج کے لیے شفٹ کا کوئی ڈیٹا دستیاب نہیں ہے',
      'no_tables_available': 'کوئی ٹیبل دستیاب نہیں ہے',
      'no_tables_found': 'کوئی ٹیبل نہیں ملی',
      'no_users_found': 'کوئی صارف نہیں ملا۔',
      'notification_settings': 'اطلاعات کی ترتیبات',
      'notification_volume': 'اطلاعات کی آواز',
      'notifications': 'اطلاعات',
      'occupied': 'مصروف',
      'occupied_status': 'مصروف',
      'of_label': 'میں سے',
      'official_receipt': 'سرکاری رسید',
      'ok': 'ٹھیک ہے',
      'online_order': 'آن لائن آرڈر',
      'operational_analytics': 'آپریشنل تجزیات',
      'operational_controls': 'آپریشنل کنٹرولز',
      'operational_controls_desc': 'ٹیکسز، فیس اور خودکار سسٹم کا انتظام کریں.',
      'operational_status': 'آپریشنل حالت',
      'operations': 'آپریشنز',
      'order_channels': 'آرڈر چینلز',
      'order_id': 'آرڈر نمبر #',
      'order_marked_status': 'آرڈر کو نشان زد کیا گیا بطور',
      'order_notifications': 'آرڈر کی اطلاعات',
      'order_notifications_desc': 'نئے آرڈرز کے لیے آواز چلائیں',
      'order_num_header': 'آرڈر نمبر #',
      'order_payment': 'آرڈر کی ادائیگی',
      'order_placed_success': '',
      'order_ready_pickup': 'آرڈر پک اپ کے لیے تیار ہے',
      'order_service_split': 'سروس کی تقسیم',
      'order_type': 'آرڈر کی قسم',
      'order_updated_success': 'آرڈر کامیابی سے اپ ڈیٹ ہو گیا!',
      'order_velocity_analytics': 'آرڈر کی رفتار کے تجزیات',
      'orders': 'آرڈرز',
      'orders_in_view': 'منظر میں آرڈر',
      'orders_management': 'آرڈرز مینجمنٹ',
      'orders_payments_reservations': 'آرڈرز، ادائیگیاں اور ریزرویشنز',
      'out_of_stock': 'اسٹاک میں نہیں ہے',
      'paid': 'ادا شدہ',
      'password': 'پاس ورڈ',
      'pax_label': 'افراد',
      'pay_all': 'سب کی ادائیگی',
      'pay_first': 'پہلے ادائیگی',
      'pay_last': 'آخر میں ادائیگی',
      'pay_now': 'ابھی ادا کریں',
      'payment_method_coverage': 'ادائیگی کا طریقہ',
      'payment_policy': 'ادائیگی کی پالیسی',
      'payment_policy_desc': 'ادائیگی کے اصول و ضوابط',
      'payment_processed': 'ادائیگی مکمل ہوگئی',
      'payment_success_message': 'ادائیگی کامیابی کے ساتھ مکمل ہو گئی ہے!',
      'payments': 'ادائیگی',
      'pending': 'زیر التواء',
      'pending_orders_kds': 'زیر التواء آرڈرز (KDS)',
      'people': 'افراد',
      'people_label': 'افراد',
      'permissions_updated': 'اجازتیں اپ ڈیٹ ہو گئیں',
      'pers_label': 'افراد',
      'phone_label': 'فون',
      'pick_up': 'پک اپ',
      'pickup': 'پک اپ',
      'please_select_table': 'براہ کرم ٹیبل منتخب کریں',
      'popular_customizations': 'مشہور تخصیصات',
      'pos': 'پی او ایس',
      'pos_system_updated': 'پی او ایس سسٹم کامیابی سے اپ ڈیٹ ہو گیا',
      'powered_by_stripe': 'Stripe کے ذریعے',
      'preparing': 'تیار ہو رہا ہے',
      'price': 'قیمت',
      'primary_currency': 'بنیادی کرنسی',
      'primary_currency_desc': 'تمام مالی لین دین اس کا استعمال کریں گے',
      'primary_logo_upload': 'پرائمری لوگو اپ لوڈ',
      'print': 'پرنٹ کریں',
      'print_all_qr': 'تمام QR کوڈز پرنٹ کریں',
      'print_now': 'ابھی پرنٹ کریں',
      'printer_desc': 'رسید پرنٹر ترتیب دیں',
      'printer_ip': 'پرنٹر آئی پی ایڈریس',
      'printer_settings': 'پرنٹر کی ترتیبات',
      'product_mix_tab': 'پروڈکٹ مکس',
      'production': 'پیداوار',
      'provide_rejection_reason': 'براہ کرم آرڈر مسترد کرنے کی وجہ بتائیں',
      'purchase_inventory_hub': 'خریداری اور انوینٹری حب',
      'purchase_management': 'خریداری کا انتظام',
      'qr_menu_order': 'QR مینو آرڈر',
      'qr_table_ordering': 'QR ٹیبل آرڈرنگ',
      'qr_table_ordering_desc': '',
      'qty': 'تعداد',
      'quick_clock_in_test': 'ٹیسٹنگ کے لیے کوئیک کلاک ان',
      'ready': 'تیار',
      'reason_required': 'وجہ ضروری ہے',
      'received_at': 'موصول ہوا وقت',
      'recent': 'حالیہ',
      'recent_activity': 'حالیہ سرگرمی',
      'recent_transactions': 'حالیہ لین دین',
      'reject_order': 'آرڈر مسترد کریں',
      'rejected': 'مسترد',
      'rejection_reason_hint': 'مثال کے طور پر: اسٹاک ختم، کچن بہت مصروف ہے...',
      'remove_user_confirm': 'کیا آپ واقعی صارف کو سسٹم سے ہٹانا چاہتے ہیں؟',
      'reports': 'رپورٹس',
      'reservation': 'ریزرویشن',
      'reservation_failed': 'ریزرویشن بنانے میں ناکامی',
      'reservation_success': 'ریزرویشن کامیابی سے بن گئی ہے!',
      'reservation_summary': 'ریزرویشن کا خلاصہ',
      'reservations': 'تحفظات',
      'reserved': 'بک شدہ',
      'reset_confirmation_detailed': '',
      'reset_transactional_data': 'ٹرانزیکشنل ڈیٹا ری سیٹ کریں',
      'reset_transactional_data_desc': '',
      'reset_warning_text': '',
      'restaurant_info': 'ریستورین کی معلومات',
      'retry': 'دوبارہ کوشش کریں',
      'retry_fetch': 'دوبارہ کوشش کریں',
      'review_confirm': 'جائزہ لیں اور تصدیق کریں',
      'role_admin': 'کردار: ایڈمنسٹریٹر',
      'role_permissions': 'کردار اور اجازتیں',
      'roles_desc': 'ہر ملازمت کے کردار کے لیے رسائی کے لیولز ترتیب دیں',
      'roles_permissions_title': 'کردار اور اجازتیں',
      'sales_log_tab': 'سیلز لاگ',
      'save': 'محفوظ کریں',
      'save_btn': 'محفوظ کریں',
      'save_changes': 'تبدیلیاں محفوظ کریں',
      'save_item': 'آئٹم محفوظ کریں',
      'save_settings': 'ترتیبات محفوظ کریں',
      'save_success': 'کامیابی سے محفوظ ہو گیا',
      'search_items': 'آئٹم تلاش کریں...',
      'search_orders': 'آرڈرز تلاش کریں',
      'search_table': 'ٹیبل نمبر تلاش کریں...',
      'seat_guest': 'مہمان کو بٹھائیں',
      'seated': 'بیٹھے ہوئے',
      'seats_label': 'نشستیں',
      'secondary_branding_desc': 'سیکنڈری برانڈنگ (مثلاً حلال لوگو)',
      'secondary_logo_upload': 'سیکنڈری لوگو اپ لوڈ',
      'security_access': 'سیکیورٹی اور رسائی',
      'select_available_table': 'دستیاب ٹیبل منتخب کریں',
      'select_booking_details': 'Select Booking Details',
      'select_date': 'تاریخ منتخب کریں',
      'select_date_range': 'تاریخ کی حد منتخب کریں',
      'select_end_date': 'ختم ہونے کی تاریخ منتخب کریں',
      'select_order_details': 'Select Order Details',
      'select_slot': 'وقت منتخب کریں',
      'select_sound': 'آواز منتخب کریں',
      'select_start_date': 'شروع کی تاریخ منتخب کریں',
      'select_table': 'ٹیبل منتخب کریں',
      'select_table_warning': 'براہ کرم ٹیبل منتخب کریں۔',
      'select_waiter': 'ویٹر منتخب کریں',
      'select_waiter_warning': 'براہ کرم ویٹر منتخب کریں۔',
      'send_test_email_btn': 'ٹیسٹ ای میل بھیجیں',
      'send_test_message': 'ٹیسٹ پیغام بھیجیں',
      'send_test_print': 'ٹیسٹ پرنٹ بھیجیں',
      'send_to_kitchen': 'کچن کو بھیجیں',
      'sender_number': 'بھیجنے والے کا نمبر',
      'sending_test_email': 'ٹیسٹ ای میل بھیج رہا ہے برائے',
      'sending_test_msg': 'ٹیسٹ پیغام بھیج رہا ہے برائے',
      'sent_to_printer': 'پرنٹر کو بھیج دیا گیا...',
      'server_error_retry': 'سرور کی خرابی۔ دوبارہ کوشش کریں۔',
      'setting_updated_success': 'ترتیب کامیابی سے اپ ڈیٹ ہو گئی',
      'settings': 'ترتیبات',
      'settings_not_loaded': 'ترتیبات لوڈ نہیں ہوئیں',
      'settings_updated_msg': 'ترتیبات کامیابی سے اپ ڈیٹ ہو گئیں!',
      'shift_label': 'شفٹ',
      'show_details': 'تفصیلات دیکھیں',
      'smtp_config': 'SMTP کنفیگریشن',
      'smtp_host': 'SMTP ہوسٹ',
      'smtp_pass': 'SMTP پاس ورڈ',
      'smtp_port': 'SMTP پورٹ',
      'smtp_setup_desc': '',
      'smtp_user': 'SMTP صارف',
      'sound_desc': 'اطلاعات کی آوازیں آن/آف کریں',
      'sound_settings': 'آواز کی ترتیبات',
      'special_requests': 'خصوصی درخواستیں / نوٹس',
      'split_bill': 'بل تقسیم کریں',
      'split_bill_dialog': 'بل تقسیم کریں',
      'split_by': 'تقسیم کریں',
      'staff_management': 'اسٹاف مینجمنٹ',
      'staff_mgmt_desc': 'اپنی ریستورین ٹیم اور رسائی کے لیولز کا انتظام کریں',
      'staff_online': 'اسٹاف آن لائن',
      'staff_tab': 'اسٹاف',
      'start_new_order': 'نیا آرڈر شروع کریں',
      'start_time_header': 'شروع ہونے کا وقت',
      'status_col': 'حالت',
      'status_header': 'حالت',
      'step_label': 'مرحلہ',
      'stock': 'اسٹاک',
      'subtotal': 'ذیلي ٹوٹل',
      'summary_tab': 'خلاصہ',
      'system_maintenance': 'سسٹم مینٹیننس',
      'system_reset': 'سسٹم ری سیٹ',
      'system_settings': 'سسٹم کی ترتیبات',
      'system_update': 'سسٹم اپ ڈیٹ',
      'table': 'ٹیبل',
      'table_added_floor': 'ٹیبل فلور پلان میں شامل کر دی گئی ہے',
      'table_label': 'ٹیبل',
      'table_layouts_settings': 'ٹیبل لے آؤٹ اور ترتیبات',
      'table_number': 'ٹیبل نمبر',
      'table_number_hint': 'ٹیبل نمبر (جیسے T15)',
      'table_qr_codes': 'ٹیبل کیو آر کوڈز',
      'table_removed': 'ٹیبل کامیابی سے ہٹا دی گئی',
      'table_size': 'ٹیبل کا سائز',
      'table_type': 'ٹیبل کی قسم',
      'table_type_header': 'ٹیبل/قسم',
      'table_updated': 'ٹیبل اپ ڈیٹ ہوگئی',
      'tables': 'ٹیبلز',
      'takeaway': 'ٹیک اوے',
      'tax': 'ٹیکس',
      'tax_rate_desc': 'سیلز ٹیکس کے لیے معیاری فیصد',
      'tax_rate_label': 'ٹیکس کی شرح (%)',
      'taxes_gratuity': 'ٹیکس اور ٹپ',
      'terminal': 'ٹرمینل',
      'terminal_id': 'ٹرمینل #',
      'test_connection': 'کنکشن جانچیں',
      'test_email_address': 'ٹیسٹ ای میل ایڈریس',
      'test_email_desc': 'ٹیسٹ ای میل بھیجنے کے لیے ای میل ایڈریس درج کریں۔',
      'test_email_success': 'کامیاب! ٹیسٹ ای میل بھیج دی گئی۔',
      'test_failed': 'ٹیسٹ ناکام',
      'test_msg_desc': 'ٹیسٹ پیغام بھیجنے کے لیے فون نمبر درج کریں۔',
      'test_msg_success': 'کامیاب! ٹیسٹ پیغام بھیج دیا گیا۔',
      'test_phone_number': 'ٹیسٹ فون نمبر',
      'test_print_sent': 'ٹیسٹ پرنٹ بھیج دیا گیا!',
      'test_smtp_msg': 'SMTP ٹیسٹ پیغام',
      'test_sound': 'آواز چیک کریں',
      'test_success': 'ٹیسٹ کامیاب',
      'test_twilio_msg': 'Twilio ٹیسٹ پیغام',
      'thank_you_visiting': 'آپ کا شکریہ!',
      'time_btn': 'وقت',
      'time_col': 'وقت',
      'time_label': 'وقت',
      'tip': 'ٹپ',
      'tips_today': 'ٹپ (آج)',
      'today_reservations': 'آج کی ریزرویشن',
      'todays_orders': 'آج کے آرڈرز',
      'todays_sale': 'آج کی فروخت',
      'top_selling_items': 'سب سے زیادہ فروخت ہونے والی اشیاء (30 دن)',
      'total': 'کل',
      'total_bill': 'کل بل',
      'total_col': 'کل',
      'total_customers': 'کل صارفین',
      'total_duration_header': 'کل دورانیہ',
      'total_orders': 'کل آرڈرز',
      'transactional_reset_success': '',
      'try_different_date': 'کوئی اور تاریخ یا وقت منتخب کرنے کی کوشش کریں۔',
      'twilio_config': 'Twilio کنفیگریشن',
      'twilio_setup_desc': 'واٹس اپ اور SMS اطلاعات کے لیے Twilio ترتیب دیں۔',
      'type_col': 'قسم',
      'unit': 'یونٹ',
      'unpaid': 'غیر ادا شدہ',
      'upcoming': 'آنے والا',
      'update_order': 'آرڈر اپ ڈیٹ کریں',
      'updating_order': 'آرڈر اپ ڈیٹ کر رہا ہے',
      'usb': 'USB',
      'user_created_success': 'صارف کامیابی سے بن گیا ہے',
      'user_deleted_success': 'صارف کامیابی سے حذف ہو گیا',
      'user_management': 'صارف کا انتظام',
      'user_profile': 'صارف کا پروفائل',
      'user_updated_success': 'صارف کامیابی سے اپ ڈیٹ ہو گیا',
      'username': 'صارف کا نام',
      'users_roles_permissions': 'صارفین، کردار اور اجازتیں',
      'uses': 'استعمال',
      'variant': 'ویریئنٹ',
      'version_label': 'ورژن',
      'view_details': 'تفصیلات دیکھیں',
      'visit_time_prompt': 'آپ کب آنا چاہیں گے؟',
      'visual_assets': 'بصری اساسیں',
      'waba_id': 'WABA ID',
      'waiting': 'انتظار',
      'waiting_status': 'انتظار کر رہا ہے',
      'website_order': 'ویب سائٹ آرڈر',
      'whatsapp_phone': 'واٹس اپ / فون',
      'will_be_deleted': 'حذف کر دیا جائے گا',
      'will_be_preserved': 'برقرار رکھا جائے گا',
    },
  };

  void setLanguage(String language) {
    final matchedKey = _translations.keys.firstWhere(
      (k) => k.toLowerCase() == language.toLowerCase(),
      orElse: () => '',
    );

    if (matchedKey.isNotEmpty) {
      _currentLanguage = matchedKey;
      notifyListeners();
    }
  }

  String translate(String key) {
    final translation = _translations[_currentLanguage]?[key];
    if (translation != null) return translation;

    return key
        .split('_')
        .map((word) {
          if (word.isEmpty) return word;
          return word[0].toUpperCase() + word.substring(1).toLowerCase();
        })
        .join(' ');
  }
}
